
// Generated by Cadence Genus(TM) Synthesis Solution 21.10-p002_1
// Generated on: May 23 2025 16:01:30 -03 (May 23 2025 19:01:30 UTC)

// Verification Directory fv/tbec_encoder 

module tbec_encoder(in_word, encoded_word);
  input [15:0] in_word;
  output [31:0] encoded_word;
  wire [15:0] in_word;
  wire [31:0] encoded_word;
  wire n_8, n_9, n_11, n_12, n_14, n_15, n_17, n_18;
  assign encoded_word[16] = in_word[0];
  assign encoded_word[17] = in_word[4];
  assign encoded_word[18] = in_word[8];
  assign encoded_word[19] = in_word[12];
  assign encoded_word[20] = in_word[1];
  assign encoded_word[21] = in_word[5];
  assign encoded_word[22] = in_word[9];
  assign encoded_word[23] = in_word[13];
  assign encoded_word[24] = in_word[2];
  assign encoded_word[25] = in_word[6];
  assign encoded_word[26] = in_word[10];
  assign encoded_word[27] = in_word[14];
  assign encoded_word[28] = in_word[3];
  assign encoded_word[29] = in_word[7];
  assign encoded_word[30] = in_word[11];
  assign encoded_word[31] = in_word[15];
  CLKXOR2X8 g250__2398(.A (n_17), .B (n_11), .Y (encoded_word[13]));
  CLKXOR2X8 g252__5107(.A (n_14), .B (n_8), .Y (encoded_word[14]));
  CLKXOR2X8 g251__6260(.A (n_18), .B (n_12), .Y (encoded_word[15]));
  CLKXOR2X8 g249__4319(.A (n_15), .B (n_9), .Y (encoded_word[12]));
  CLKXOR2X8 g253__8428(.A (n_18), .B (n_17), .Y (encoded_word[9]));
  CLKXOR2X8 g254__5526(.A (n_15), .B (n_14), .Y (encoded_word[10]));
  CLKXOR2X8 g255__6783(.A (n_12), .B (n_11), .Y (encoded_word[11]));
  CLKXOR2X8 g256__3680(.A (n_9), .B (n_8), .Y (encoded_word[8]));
  CLKXOR2X8 g257__1617(.A (in_word[13]), .B (in_word[15]), .Y
       (encoded_word[7]));
  CLKXOR2X8 g265__2802(.A (in_word[1]), .B (in_word[3]), .Y
       (encoded_word[1]));
  CLKXOR2X8 g266__1705(.A (in_word[0]), .B (in_word[2]), .Y
       (encoded_word[0]));
  CLKXOR2X8 g267__5122(.A (in_word[4]), .B (in_word[6]), .Y
       (encoded_word[2]));
  XNOR2X1 g268__8246(.A (in_word[0]), .B (in_word[5]), .Y (n_15));
  XNOR2X1 g271__7098(.A (in_word[1]), .B (in_word[4]), .Y (n_14));
  XNOR2X1 g263__6131(.A (in_word[3]), .B (in_word[6]), .Y (n_17));
  XNOR2X1 g270__1881(.A (in_word[8]), .B (in_word[13]), .Y (n_9));
  CLKXOR2X8 g258__5115(.A (in_word[9]), .B (in_word[11]), .Y
       (encoded_word[5]));
  CLKXOR2X8 g261__7482(.A (in_word[5]), .B (in_word[7]), .Y
       (encoded_word[3]));
  CLKXOR2X8 g260__4733(.A (in_word[8]), .B (in_word[10]), .Y
       (encoded_word[4]));
  CLKXOR2X8 g259__6161(.A (in_word[12]), .B (in_word[14]), .Y
       (encoded_word[6]));
  XNOR2X1 g269__9315(.A (in_word[11]), .B (in_word[14]), .Y (n_11));
  XNOR2X1 g272__9945(.A (in_word[9]), .B (in_word[12]), .Y (n_8));
  XNOR2X1 g264__2883(.A (in_word[10]), .B (in_word[15]), .Y (n_12));
  XNOR2X1 g262__2346(.A (in_word[2]), .B (in_word[7]), .Y (n_18));
endmodule

