
// Generated by Cadence Genus(TM) Synthesis Solution 21.10-p002_1
// Generated on: May 28 2025 16:48:02 -03 (May 28 2025 19:48:02 UTC)

// Verification Directory fv/tbec_full 

module tbec_memory(clk, we, addr, data_in, data_out);
  input clk, we;
  input [7:0] addr;
  input [31:0] data_in;
  output [31:0] data_out;
  wire clk, we;
  wire [7:0] addr;
  wire [31:0] data_in;
  wire [31:0] data_out;
  wire [31:0] \mem_data[6] ;
  wire [31:0] \mem_data[7] ;
  wire [31:0] \mem_data[4] ;
  wire [31:0] \mem_data[2] ;
  wire [31:0] \mem_data[3] ;
  wire [31:0] \mem_data[0] ;
  wire [31:0] \mem_data[1] ;
  wire [31:0] \mem_data[5] ;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_77, n_78, n_79;
  wire n_80, n_81, n_82, n_83, n_84, n_85, n_86, n_87;
  wire n_88, n_89, n_90, n_91, n_92, n_93, n_94, n_95;
  wire n_96, n_97, n_98, n_99, n_100, n_101, n_102, n_103;
  wire n_104, n_105, n_106, n_107, n_108, n_109, n_110, n_111;
  wire n_112, n_113, n_114, n_115, n_116, n_117, n_118, n_119;
  wire n_120, n_121, n_122, n_123, n_124, n_125, n_126, n_127;
  wire n_128, n_129, n_130, n_131, n_132, n_133, n_134, n_135;
  wire n_136, n_137, n_138, n_139, n_140, n_141, n_142, n_143;
  wire n_144, n_145, n_146, n_147, n_148, n_149, n_150, n_151;
  wire n_152, n_153, n_154, n_155, n_156, n_157, n_158, n_159;
  wire n_160, n_161, n_162, n_163, n_164, n_165, n_166, n_167;
  wire n_168, n_169, n_170, n_171, n_172, n_173, n_174, n_175;
  wire n_176, n_177, n_178, n_179, n_180, n_181, n_182, n_183;
  wire n_184, n_185, n_992_BAR, n_1005_BAR, n_1009_BAR, n_1013_BAR,
       n_1015_BAR, n_1017_BAR;
  wire n_1019_BAR, n_1021_BAR;
  NAND3X2 g3854__2398(.A (n_103), .B (n_106), .C (n_170), .Y (n_185));
  OR4X1 g3855__5107(.A (n_102), .B (n_52), .C (n_47), .D (n_75), .Y
       (data_out[30]));
  OR4X1 g3856__6260(.A (n_141), .B (n_130), .C (n_127), .D (n_148), .Y
       (data_out[26]));
  OR4X1 g3857__4319(.A (n_137), .B (n_147), .C (n_138), .D (n_143), .Y
       (data_out[20]));
  NAND3X2 g3858__8428(.A (n_150), .B (n_152), .C (n_164), .Y (n_184));
  NAND3X2 g3859__5526(.A (n_20), .B (n_142), .C (n_169), .Y (n_183));
  NAND3X2 g3860__6783(.A (n_135), .B (n_136), .C (n_168), .Y (n_182));
  OR4X1 g3861__3680(.A (n_96), .B (n_121), .C (n_105), .D (n_112), .Y
       (data_out[25]));
  OR4X1 g3862__1617(.A (n_132), .B (n_119), .C (n_126), .D (n_155), .Y
       (data_out[19]));
  NAND3X2 g3863__2802(.A (n_125), .B (n_129), .C (n_167), .Y (n_181));
  OR4X1 g3864__1705(.A (n_104), .B (n_115), .C (n_107), .D (n_111), .Y
       (data_out[18]));
  NAND3X2 g3865__5122(.A (n_120), .B (n_12), .C (n_166), .Y (n_180));
  NAND3X2 g3866__8246(.A (n_114), .B (n_16), .C (n_165), .Y (n_179));
  OR4X1 g3867__7098(.A (n_78), .B (n_63), .C (n_97), .D (n_67), .Y
       (data_out[28]));
  OR4X1 g3868__6131(.A (n_88), .B (n_93), .C (n_101), .D (n_95), .Y
       (data_out[17]));
  OR4X1 g3869__1881(.A (n_134), .B (n_36), .C (n_69), .D (n_59), .Y
       (data_out[31]));
  NAND3X2 g3870__5115(.A (n_32), .B (n_19), .C (n_156), .Y (n_178));
  OR4X1 g3871__7482(.A (n_71), .B (n_73), .C (n_80), .D (n_89), .Y
       (data_out[24]));
  OR4X1 g3872__4733(.A (n_82), .B (n_76), .C (n_74), .D (n_85), .Y
       (data_out[16]));
  NAND3X2 g3873__6161(.A (n_90), .B (n_13), .C (n_162), .Y (n_177));
  NAND3X2 g3874__9315(.A (n_21), .B (n_83), .C (n_161), .Y (n_176));
  OR4X1 g3875__9945(.A (n_145), .B (n_113), .C (n_31), .D (n_128), .Y
       (data_out[29]));
  OR4X1 g3876__2883(.A (n_30), .B (n_46), .C (n_55), .D (n_39), .Y
       (data_out[27]));
  OR4X1 g3877__2346(.A (n_65), .B (n_54), .C (n_61), .D (n_57), .Y
       (data_out[23]));
  NAND3X2 g3878__1666(.A (n_17), .B (n_68), .C (n_160), .Y (n_175));
  NAND3X2 g3879__7410(.A (n_14), .B (n_60), .C (n_163), .Y (n_174));
  OR4X1 g3880__6417(.A (n_41), .B (n_49), .C (n_38), .D (n_45), .Y
       (data_out[22]));
  NAND3X2 g3881__5477(.A (n_56), .B (n_22), .C (n_158), .Y (n_173));
  OR4X1 g3882__2398(.A (n_151), .B (n_123), .C (n_34), .D (n_29), .Y
       (data_out[21]));
  NAND3X2 g3883__5107(.A (n_48), .B (n_18), .C (n_157), .Y (n_172));
  OR4X1 g3884__6260(.A (n_33), .B (n_35), .C (n_40), .D (n_37), .Y
       (data_out[11]));
  NAND3X2 g3885__4319(.A (n_15), .B (n_72), .C (n_159), .Y (n_171));
  AND2X1 g3886__8428(.A (n_99), .B (n_100), .Y (n_170));
  AND2X1 g3887__5526(.A (n_140), .B (n_139), .Y (n_169));
  AND2X1 g3888__6783(.A (n_133), .B (n_131), .Y (n_168));
  AND2X1 g3889__3680(.A (n_124), .B (n_122), .Y (n_167));
  AND2X1 g3890__1617(.A (n_116), .B (n_117), .Y (n_166));
  AND2X1 g3891__2802(.A (n_109), .B (n_108), .Y (n_165));
  AND2X1 g3892__1705(.A (n_146), .B (n_149), .Y (n_164));
  AND2X1 g3893__5122(.A (n_91), .B (n_58), .Y (n_163));
  AND2X1 g3894__8246(.A (n_84), .B (n_86), .Y (n_162));
  AND2X1 g3895__7098(.A (n_79), .B (n_77), .Y (n_161));
  AND2X1 g3896__6131(.A (n_66), .B (n_64), .Y (n_160));
  AND2X1 g3897__1881(.A (n_92), .B (n_94), .Y (n_159));
  AND2X1 g3898__5115(.A (n_51), .B (n_50), .Y (n_158));
  AND2X1 g3899__7482(.A (n_42), .B (n_43), .Y (n_157));
  AND2X1 g3900__4733(.A (n_153), .B (n_154), .Y (n_156));
  AO22X1 g3901__6161(.A0 (\mem_data[6] [19]), .A1 (n_1013_BAR), .B0
       (\mem_data[7] [19]), .B1 (n_1005_BAR), .Y (n_155));
  AOI22X1 g3902__9315(.A0 (\mem_data[4] [10]), .A1 (n_1015_BAR), .B0
       (\mem_data[7] [10]), .B1 (n_1005_BAR), .Y (n_154));
  AOI22X1 g3903__9945(.A0 (\mem_data[2] [10]), .A1 (n_1019_BAR), .B0
       (\mem_data[3] [10]), .B1 (n_992_BAR), .Y (n_153));
  AOI22X1 g3904__2883(.A0 (\mem_data[4] [9]), .A1 (n_1015_BAR), .B0
       (\mem_data[7] [9]), .B1 (n_1005_BAR), .Y (n_152));
  AO22X1 g3905__2346(.A0 (\mem_data[0] [21]), .A1 (n_1021_BAR), .B0
       (\mem_data[1] [21]), .B1 (n_1009_BAR), .Y (n_151));
  AOI22X1 g3906__1666(.A0 (\mem_data[0] [9]), .A1 (n_1021_BAR), .B0
       (\mem_data[1] [9]), .B1 (n_1009_BAR), .Y (n_150));
  AOI22X1 g3907__7410(.A0 (\mem_data[5] [9]), .A1 (n_1017_BAR), .B0
       (\mem_data[6] [9]), .B1 (n_1013_BAR), .Y (n_149));
  AO22X1 g3908__6417(.A0 (\mem_data[5] [26]), .A1 (n_1017_BAR), .B0
       (\mem_data[7] [26]), .B1 (n_1005_BAR), .Y (n_148));
  AO22X1 g3909__5477(.A0 (\mem_data[2] [20]), .A1 (n_1019_BAR), .B0
       (\mem_data[3] [20]), .B1 (n_992_BAR), .Y (n_147));
  AOI22X1 g3910__2398(.A0 (\mem_data[2] [9]), .A1 (n_1019_BAR), .B0
       (\mem_data[3] [9]), .B1 (n_992_BAR), .Y (n_146));
  AO22X1 g3911__5107(.A0 (\mem_data[1] [29]), .A1 (n_1009_BAR), .B0
       (\mem_data[2] [29]), .B1 (n_1019_BAR), .Y (n_145));
  AOI22X1 g3912__6260(.A0 (\mem_data[5] [8]), .A1 (n_1017_BAR), .B0
       (\mem_data[6] [8]), .B1 (n_1013_BAR), .Y (n_144));
  AO22X1 g3913__4319(.A0 (\mem_data[5] [20]), .A1 (n_1017_BAR), .B0
       (\mem_data[6] [20]), .B1 (n_1013_BAR), .Y (n_143));
  AOI22X1 g3914__8428(.A0 (\mem_data[2] [8]), .A1 (n_1019_BAR), .B0
       (\mem_data[3] [8]), .B1 (n_992_BAR), .Y (n_142));
  AO22X1 g3915__5526(.A0 (\mem_data[0] [26]), .A1 (n_1021_BAR), .B0
       (\mem_data[2] [26]), .B1 (n_1019_BAR), .Y (n_141));
  AOI22X1 g3916__6783(.A0 (\mem_data[4] [8]), .A1 (n_1015_BAR), .B0
       (\mem_data[7] [8]), .B1 (n_1005_BAR), .Y (n_140));
  AOI22X1 g3917__3680(.A0 (\mem_data[0] [8]), .A1 (n_1021_BAR), .B0
       (\mem_data[1] [8]), .B1 (n_1009_BAR), .Y (n_139));
  AO22X1 g3918__1617(.A0 (\mem_data[4] [20]), .A1 (n_1015_BAR), .B0
       (\mem_data[7] [20]), .B1 (n_1005_BAR), .Y (n_138));
  AO22X1 g3919__2802(.A0 (\mem_data[0] [20]), .A1 (n_1021_BAR), .B0
       (\mem_data[1] [20]), .B1 (n_1009_BAR), .Y (n_137));
  AOI22X1 g3920__1705(.A0 (\mem_data[2] [7]), .A1 (n_1019_BAR), .B0
       (\mem_data[3] [7]), .B1 (n_992_BAR), .Y (n_136));
  AOI22X1 g3921__5122(.A0 (\mem_data[0] [7]), .A1 (n_1021_BAR), .B0
       (\mem_data[1] [7]), .B1 (n_1009_BAR), .Y (n_135));
  AO22X1 g3922__8246(.A0 (\mem_data[1] [31]), .A1 (n_1009_BAR), .B0
       (\mem_data[2] [31]), .B1 (n_1019_BAR), .Y (n_134));
  AOI22X1 g3923__7098(.A0 (\mem_data[5] [7]), .A1 (n_1017_BAR), .B0
       (\mem_data[6] [7]), .B1 (n_1013_BAR), .Y (n_133));
  AO22X1 g3924__6131(.A0 (\mem_data[0] [19]), .A1 (n_1021_BAR), .B0
       (\mem_data[1] [19]), .B1 (n_1009_BAR), .Y (n_132));
  AOI22X1 g3925__1881(.A0 (\mem_data[4] [7]), .A1 (n_1015_BAR), .B0
       (\mem_data[7] [7]), .B1 (n_1005_BAR), .Y (n_131));
  AO22X1 g3926__5115(.A0 (\mem_data[4] [26]), .A1 (n_1015_BAR), .B0
       (\mem_data[3] [26]), .B1 (n_992_BAR), .Y (n_130));
  AOI22X1 g3927__7482(.A0 (\mem_data[2] [6]), .A1 (n_1019_BAR), .B0
       (\mem_data[3] [6]), .B1 (n_992_BAR), .Y (n_129));
  AO22X1 g3928__4733(.A0 (\mem_data[5] [29]), .A1 (n_1017_BAR), .B0
       (\mem_data[6] [29]), .B1 (n_1013_BAR), .Y (n_128));
  AO22X1 g3929__6161(.A0 (\mem_data[1] [26]), .A1 (n_1009_BAR), .B0
       (\mem_data[6] [26]), .B1 (n_1013_BAR), .Y (n_127));
  AO22X1 g3930__9315(.A0 (\mem_data[4] [19]), .A1 (n_1015_BAR), .B0
       (\mem_data[3] [19]), .B1 (n_992_BAR), .Y (n_126));
  AOI22X1 g3931__9945(.A0 (\mem_data[0] [6]), .A1 (n_1021_BAR), .B0
       (\mem_data[1] [6]), .B1 (n_1009_BAR), .Y (n_125));
  AOI22X1 g3932__2883(.A0 (\mem_data[5] [6]), .A1 (n_1017_BAR), .B0
       (\mem_data[6] [6]), .B1 (n_1013_BAR), .Y (n_124));
  AO22X1 g3933__2346(.A0 (\mem_data[2] [21]), .A1 (n_1019_BAR), .B0
       (\mem_data[3] [21]), .B1 (n_992_BAR), .Y (n_123));
  AOI22X1 g3934__1666(.A0 (\mem_data[4] [6]), .A1 (n_1015_BAR), .B0
       (\mem_data[7] [6]), .B1 (n_1005_BAR), .Y (n_122));
  AO22X1 g3935__7410(.A0 (\mem_data[0] [25]), .A1 (n_1021_BAR), .B0
       (\mem_data[5] [25]), .B1 (n_1017_BAR), .Y (n_121));
  AOI22X1 g3936__6417(.A0 (\mem_data[0] [5]), .A1 (n_1021_BAR), .B0
       (\mem_data[1] [5]), .B1 (n_1009_BAR), .Y (n_120));
  AO22X1 g3937__5477(.A0 (\mem_data[2] [19]), .A1 (n_1019_BAR), .B0
       (\mem_data[5] [19]), .B1 (n_1017_BAR), .Y (n_119));
  AOI22X1 g3938__2398(.A0 (\mem_data[6] [5]), .A1 (n_1013_BAR), .B0
       (\mem_data[7] [5]), .B1 (n_1005_BAR), .Y (n_118));
  AOI22X1 g3939__5107(.A0 (\mem_data[2] [5]), .A1 (n_1019_BAR), .B0
       (\mem_data[3] [5]), .B1 (n_992_BAR), .Y (n_117));
  AOI22X1 g3940__6260(.A0 (\mem_data[4] [5]), .A1 (n_1015_BAR), .B0
       (\mem_data[5] [5]), .B1 (n_1017_BAR), .Y (n_116));
  AO22X1 g3941__4319(.A0 (\mem_data[4] [18]), .A1 (n_1015_BAR), .B0
       (\mem_data[3] [18]), .B1 (n_992_BAR), .Y (n_115));
  AOI22X1 g3942__8428(.A0 (\mem_data[0] [4]), .A1 (n_1021_BAR), .B0
       (\mem_data[5] [4]), .B1 (n_1017_BAR), .Y (n_114));
  AO22X1 g3943__5526(.A0 (\mem_data[4] [29]), .A1 (n_1015_BAR), .B0
       (\mem_data[3] [29]), .B1 (n_992_BAR), .Y (n_113));
  AO22X1 g3944__6783(.A0 (\mem_data[6] [25]), .A1 (n_1013_BAR), .B0
       (\mem_data[7] [25]), .B1 (n_1005_BAR), .Y (n_112));
  AO22X1 g3945__3680(.A0 (\mem_data[0] [18]), .A1 (n_1021_BAR), .B0
       (\mem_data[6] [18]), .B1 (n_1013_BAR), .Y (n_111));
  AOI22X1 g3946__1617(.A0 (\mem_data[6] [4]), .A1 (n_1013_BAR), .B0
       (\mem_data[7] [4]), .B1 (n_1005_BAR), .Y (n_110));
  AOI22X1 g3947__2802(.A0 (\mem_data[4] [4]), .A1 (n_1015_BAR), .B0
       (\mem_data[3] [4]), .B1 (n_992_BAR), .Y (n_109));
  AOI22X1 g3948__1705(.A0 (\mem_data[1] [4]), .A1 (n_1009_BAR), .B0
       (\mem_data[2] [4]), .B1 (n_1019_BAR), .Y (n_108));
  AO22X1 g3949__5122(.A0 (\mem_data[5] [18]), .A1 (n_1017_BAR), .B0
       (\mem_data[7] [18]), .B1 (n_1005_BAR), .Y (n_107));
  AOI22X1 g3950__8246(.A0 (\mem_data[2] [3]), .A1 (n_1019_BAR), .B0
       (\mem_data[3] [3]), .B1 (n_992_BAR), .Y (n_106));
  AO22X1 g3951__7098(.A0 (\mem_data[4] [25]), .A1 (n_1015_BAR), .B0
       (\mem_data[3] [25]), .B1 (n_992_BAR), .Y (n_105));
  AO22X1 g3952__6131(.A0 (\mem_data[1] [18]), .A1 (n_1009_BAR), .B0
       (\mem_data[2] [18]), .B1 (n_1019_BAR), .Y (n_104));
  AOI22X1 g3953__1881(.A0 (\mem_data[0] [3]), .A1 (n_1021_BAR), .B0
       (\mem_data[1] [3]), .B1 (n_1009_BAR), .Y (n_103));
  AO22X1 g3954__5115(.A0 (\mem_data[0] [30]), .A1 (n_1021_BAR), .B0
       (\mem_data[1] [30]), .B1 (n_1009_BAR), .Y (n_102));
  AO22X1 g3955__7482(.A0 (\mem_data[4] [17]), .A1 (n_1015_BAR), .B0
       (\mem_data[7] [17]), .B1 (n_1005_BAR), .Y (n_101));
  AOI22X1 g3956__4733(.A0 (\mem_data[6] [3]), .A1 (n_1013_BAR), .B0
       (\mem_data[7] [3]), .B1 (n_1005_BAR), .Y (n_100));
  AOI22X1 g3957__6161(.A0 (\mem_data[4] [3]), .A1 (n_1015_BAR), .B0
       (\mem_data[5] [3]), .B1 (n_1017_BAR), .Y (n_99));
  AOI22X1 g3958__9315(.A0 (\mem_data[1] [2]), .A1 (n_1009_BAR), .B0
       (\mem_data[2] [2]), .B1 (n_1019_BAR), .Y (n_98));
  AO22X1 g3959__9945(.A0 (\mem_data[4] [28]), .A1 (n_1015_BAR), .B0
       (\mem_data[3] [28]), .B1 (n_992_BAR), .Y (n_97));
  AO22X1 g3960__2883(.A0 (\mem_data[1] [25]), .A1 (n_1009_BAR), .B0
       (\mem_data[2] [25]), .B1 (n_1019_BAR), .Y (n_96));
  AO22X1 g3961__2346(.A0 (\mem_data[5] [17]), .A1 (n_1017_BAR), .B0
       (\mem_data[6] [17]), .B1 (n_1013_BAR), .Y (n_95));
  AOI22X1 g3962__1666(.A0 (\mem_data[5] [2]), .A1 (n_1017_BAR), .B0
       (\mem_data[7] [2]), .B1 (n_1005_BAR), .Y (n_94));
  AO22X1 g3963__7410(.A0 (\mem_data[2] [17]), .A1 (n_1019_BAR), .B0
       (\mem_data[3] [17]), .B1 (n_992_BAR), .Y (n_93));
  AOI22X1 g3964__6417(.A0 (\mem_data[4] [2]), .A1 (n_1015_BAR), .B0
       (\mem_data[3] [2]), .B1 (n_992_BAR), .Y (n_92));
  AOI22X1 g3965__5477(.A0 (\mem_data[4] [14]), .A1 (n_1015_BAR), .B0
       (\mem_data[5] [14]), .B1 (n_1017_BAR), .Y (n_91));
  AOI22X1 g3966__2398(.A0 (\mem_data[0] [1]), .A1 (n_1021_BAR), .B0
       (\mem_data[1] [1]), .B1 (n_1009_BAR), .Y (n_90));
  AO22X1 g3967__5107(.A0 (\mem_data[6] [24]), .A1 (n_1013_BAR), .B0
       (\mem_data[7] [24]), .B1 (n_1005_BAR), .Y (n_89));
  AO22X1 g3968__6260(.A0 (\mem_data[0] [17]), .A1 (n_1021_BAR), .B0
       (\mem_data[1] [17]), .B1 (n_1009_BAR), .Y (n_88));
  AOI22X1 g3969__4319(.A0 (\mem_data[6] [1]), .A1 (n_1013_BAR), .B0
       (\mem_data[7] [1]), .B1 (n_1005_BAR), .Y (n_87));
  AOI22X1 g3970__8428(.A0 (\mem_data[5] [1]), .A1 (n_1017_BAR), .B0
       (\mem_data[3] [1]), .B1 (n_992_BAR), .Y (n_86));
  AO22X1 g3971__5526(.A0 (\mem_data[5] [16]), .A1 (n_1017_BAR), .B0
       (\mem_data[7] [16]), .B1 (n_1005_BAR), .Y (n_85));
  AOI22X1 g3972__6783(.A0 (\mem_data[4] [1]), .A1 (n_1015_BAR), .B0
       (\mem_data[2] [1]), .B1 (n_1019_BAR), .Y (n_84));
  AOI22X1 g3973__3680(.A0 (\mem_data[4] [0]), .A1 (n_1015_BAR), .B0
       (\mem_data[6] [0]), .B1 (n_1013_BAR), .Y (n_83));
  AO22X1 g3974__1617(.A0 (\mem_data[1] [16]), .A1 (n_1009_BAR), .B0
       (\mem_data[2] [16]), .B1 (n_1019_BAR), .Y (n_82));
  AOI22X1 g3975__2802(.A0 (\mem_data[5] [0]), .A1 (n_1017_BAR), .B0
       (\mem_data[7] [0]), .B1 (n_1005_BAR), .Y (n_81));
  AO22X1 g3976__1705(.A0 (\mem_data[2] [24]), .A1 (n_1019_BAR), .B0
       (\mem_data[3] [24]), .B1 (n_992_BAR), .Y (n_80));
  AOI22X1 g3977__5122(.A0 (\mem_data[2] [0]), .A1 (n_1019_BAR), .B0
       (\mem_data[3] [0]), .B1 (n_992_BAR), .Y (n_79));
  AO22X1 g3978__8246(.A0 (\mem_data[1] [28]), .A1 (n_1009_BAR), .B0
       (\mem_data[2] [28]), .B1 (n_1019_BAR), .Y (n_78));
  AOI22X1 g3979__7098(.A0 (\mem_data[0] [0]), .A1 (n_1021_BAR), .B0
       (\mem_data[1] [0]), .B1 (n_1009_BAR), .Y (n_77));
  AO22X1 g3980__6131(.A0 (\mem_data[4] [16]), .A1 (n_1015_BAR), .B0
       (\mem_data[3] [16]), .B1 (n_992_BAR), .Y (n_76));
  AO22X1 g3981__1881(.A0 (\mem_data[5] [30]), .A1 (n_1017_BAR), .B0
       (\mem_data[7] [30]), .B1 (n_1005_BAR), .Y (n_75));
  AO22X1 g3982__5115(.A0 (\mem_data[0] [16]), .A1 (n_1021_BAR), .B0
       (\mem_data[6] [16]), .B1 (n_1013_BAR), .Y (n_74));
  AO22X1 g3983__7482(.A0 (\mem_data[4] [24]), .A1 (n_1015_BAR), .B0
       (\mem_data[5] [24]), .B1 (n_1017_BAR), .Y (n_73));
  AOI22X1 g3984__4733(.A0 (\mem_data[0] [2]), .A1 (n_1021_BAR), .B0
       (\mem_data[6] [2]), .B1 (n_1013_BAR), .Y (n_72));
  AO22X1 g3985__6161(.A0 (\mem_data[0] [24]), .A1 (n_1021_BAR), .B0
       (\mem_data[1] [24]), .B1 (n_1009_BAR), .Y (n_71));
  AOI22X1 g3986__9315(.A0 (\mem_data[6] [15]), .A1 (n_1013_BAR), .B0
       (\mem_data[7] [15]), .B1 (n_1005_BAR), .Y (n_70));
  AO22X1 g3987__9945(.A0 (\mem_data[0] [31]), .A1 (n_1021_BAR), .B0
       (\mem_data[7] [31]), .B1 (n_1005_BAR), .Y (n_69));
  AOI22X1 g3988__2883(.A0 (\mem_data[4] [15]), .A1 (n_1015_BAR), .B0
       (\mem_data[5] [15]), .B1 (n_1017_BAR), .Y (n_68));
  AO22X1 g3989__2346(.A0 (\mem_data[5] [28]), .A1 (n_1017_BAR), .B0
       (\mem_data[6] [28]), .B1 (n_1013_BAR), .Y (n_67));
  AOI22X1 g3990__1666(.A0 (\mem_data[2] [15]), .A1 (n_1019_BAR), .B0
       (\mem_data[3] [15]), .B1 (n_992_BAR), .Y (n_66));
  AO22X1 g3991__7410(.A0 (\mem_data[0] [23]), .A1 (n_1021_BAR), .B0
       (\mem_data[1] [23]), .B1 (n_1009_BAR), .Y (n_65));
  AOI22X1 g3992__6417(.A0 (\mem_data[0] [15]), .A1 (n_1021_BAR), .B0
       (\mem_data[1] [15]), .B1 (n_1009_BAR), .Y (n_64));
  AO22X1 g3993__5477(.A0 (\mem_data[0] [28]), .A1 (n_1021_BAR), .B0
       (\mem_data[7] [28]), .B1 (n_1005_BAR), .Y (n_63));
  AOI22X1 g3994__2398(.A0 (\mem_data[6] [14]), .A1 (n_1013_BAR), .B0
       (\mem_data[7] [14]), .B1 (n_1005_BAR), .Y (n_62));
  AO22X1 g3995__5107(.A0 (\mem_data[2] [23]), .A1 (n_1019_BAR), .B0
       (\mem_data[3] [23]), .B1 (n_992_BAR), .Y (n_61));
  AOI22X1 g3996__6260(.A0 (\mem_data[2] [14]), .A1 (n_1019_BAR), .B0
       (\mem_data[3] [14]), .B1 (n_992_BAR), .Y (n_60));
  AO22X1 g3997__4319(.A0 (\mem_data[5] [31]), .A1 (n_1017_BAR), .B0
       (\mem_data[6] [31]), .B1 (n_1013_BAR), .Y (n_59));
  AOI22X1 g3998__8428(.A0 (\mem_data[0] [14]), .A1 (n_1021_BAR), .B0
       (\mem_data[1] [14]), .B1 (n_1009_BAR), .Y (n_58));
  AO22X1 g3999__5526(.A0 (\mem_data[6] [23]), .A1 (n_1013_BAR), .B0
       (\mem_data[7] [23]), .B1 (n_1005_BAR), .Y (n_57));
  AOI22X1 g4000__6783(.A0 (\mem_data[4] [13]), .A1 (n_1015_BAR), .B0
       (\mem_data[7] [13]), .B1 (n_1005_BAR), .Y (n_56));
  AO22X1 g4001__3680(.A0 (\mem_data[4] [27]), .A1 (n_1015_BAR), .B0
       (\mem_data[5] [27]), .B1 (n_1017_BAR), .Y (n_55));
  AO22X1 g4002__1617(.A0 (\mem_data[4] [23]), .A1 (n_1015_BAR), .B0
       (\mem_data[5] [23]), .B1 (n_1017_BAR), .Y (n_54));
  AOI22X1 g4003__2802(.A0 (\mem_data[5] [13]), .A1 (n_1017_BAR), .B0
       (\mem_data[6] [13]), .B1 (n_1013_BAR), .Y (n_53));
  AO22X1 g4004__1705(.A0 (\mem_data[2] [30]), .A1 (n_1019_BAR), .B0
       (\mem_data[3] [30]), .B1 (n_992_BAR), .Y (n_52));
  AOI22X1 g4005__5122(.A0 (\mem_data[2] [13]), .A1 (n_1019_BAR), .B0
       (\mem_data[3] [13]), .B1 (n_992_BAR), .Y (n_51));
  AOI22X1 g4006__8246(.A0 (\mem_data[0] [13]), .A1 (n_1021_BAR), .B0
       (\mem_data[1] [13]), .B1 (n_1009_BAR), .Y (n_50));
  AO22X1 g4007__7098(.A0 (\mem_data[4] [22]), .A1 (n_1015_BAR), .B0
       (\mem_data[3] [22]), .B1 (n_992_BAR), .Y (n_49));
  AOI22X1 g4008__6131(.A0 (\mem_data[0] [12]), .A1 (n_1021_BAR), .B0
       (\mem_data[1] [12]), .B1 (n_1009_BAR), .Y (n_48));
  AO22X1 g4009__1881(.A0 (\mem_data[4] [30]), .A1 (n_1015_BAR), .B0
       (\mem_data[6] [30]), .B1 (n_1013_BAR), .Y (n_47));
  AO22X1 g4010__5115(.A0 (\mem_data[2] [27]), .A1 (n_1019_BAR), .B0
       (\mem_data[3] [27]), .B1 (n_992_BAR), .Y (n_46));
  AO22X1 g4011__7482(.A0 (\mem_data[5] [22]), .A1 (n_1017_BAR), .B0
       (\mem_data[7] [22]), .B1 (n_1005_BAR), .Y (n_45));
  AOI22X1 g4012__4733(.A0 (\mem_data[5] [12]), .A1 (n_1017_BAR), .B0
       (\mem_data[6] [12]), .B1 (n_1013_BAR), .Y (n_44));
  AOI22X1 g4013__6161(.A0 (\mem_data[4] [12]), .A1 (n_1015_BAR), .B0
       (\mem_data[7] [12]), .B1 (n_1005_BAR), .Y (n_43));
  AOI22X1 g4014__9315(.A0 (\mem_data[2] [12]), .A1 (n_1019_BAR), .B0
       (\mem_data[3] [12]), .B1 (n_992_BAR), .Y (n_42));
  AO22X1 g4015__9945(.A0 (\mem_data[1] [22]), .A1 (n_1009_BAR), .B0
       (\mem_data[2] [22]), .B1 (n_1019_BAR), .Y (n_41));
  AO22X1 g4016__2883(.A0 (\mem_data[4] [11]), .A1 (n_1015_BAR), .B0
       (\mem_data[7] [11]), .B1 (n_1005_BAR), .Y (n_40));
  AO22X1 g4017__2346(.A0 (\mem_data[6] [27]), .A1 (n_1013_BAR), .B0
       (\mem_data[7] [27]), .B1 (n_1005_BAR), .Y (n_39));
  AO22X1 g4018__1666(.A0 (\mem_data[0] [22]), .A1 (n_1021_BAR), .B0
       (\mem_data[6] [22]), .B1 (n_1013_BAR), .Y (n_38));
  AO22X1 g4019__7410(.A0 (\mem_data[5] [11]), .A1 (n_1017_BAR), .B0
       (\mem_data[6] [11]), .B1 (n_1013_BAR), .Y (n_37));
  AO22X1 g4020__6417(.A0 (\mem_data[4] [31]), .A1 (n_1015_BAR), .B0
       (\mem_data[3] [31]), .B1 (n_992_BAR), .Y (n_36));
  AO22X1 g4021__5477(.A0 (\mem_data[2] [11]), .A1 (n_1019_BAR), .B0
       (\mem_data[3] [11]), .B1 (n_992_BAR), .Y (n_35));
  AO22X1 g4022__2398(.A0 (\mem_data[4] [21]), .A1 (n_1015_BAR), .B0
       (\mem_data[7] [21]), .B1 (n_1005_BAR), .Y (n_34));
  AO22X1 g4023__5107(.A0 (\mem_data[0] [11]), .A1 (n_1021_BAR), .B0
       (\mem_data[1] [11]), .B1 (n_1009_BAR), .Y (n_33));
  AOI22X1 g4024__6260(.A0 (\mem_data[0] [10]), .A1 (n_1021_BAR), .B0
       (\mem_data[1] [10]), .B1 (n_1009_BAR), .Y (n_32));
  AO22X1 g4025__4319(.A0 (\mem_data[0] [29]), .A1 (n_1021_BAR), .B0
       (\mem_data[7] [29]), .B1 (n_1005_BAR), .Y (n_31));
  AO22X1 g4026__8428(.A0 (\mem_data[0] [27]), .A1 (n_1021_BAR), .B0
       (\mem_data[1] [27]), .B1 (n_1009_BAR), .Y (n_30));
  AO22X1 g4027__5526(.A0 (\mem_data[5] [21]), .A1 (n_1017_BAR), .B0
       (\mem_data[6] [21]), .B1 (n_1013_BAR), .Y (n_29));
  AOI22X1 g4028__6783(.A0 (\mem_data[5] [10]), .A1 (n_1017_BAR), .B0
       (\mem_data[6] [10]), .B1 (n_1013_BAR), .Y (n_28));
  AND2X6 g4029__3680(.A (addr[0]), .B (n_27), .Y (n_1009_BAR));
  CLKAND2X12 g4030__1617(.A (n_23), .B (n_26), .Y (n_1019_BAR));
  AND2X6 g4031__2802(.A (addr[0]), .B (n_26), .Y (n_992_BAR));
  AND2X6 g4032__1705(.A (n_23), .B (n_24), .Y (n_1013_BAR));
  CLKAND2X12 g4033__5122(.A (n_23), .B (n_27), .Y (n_1021_BAR));
  AND2X6 g4034__8246(.A (addr[0]), .B (n_24), .Y (n_1005_BAR));
  AND2X6 g4035__7098(.A (addr[0]), .B (n_25), .Y (n_1017_BAR));
  CLKAND2X12 g4036__6131(.A (n_23), .B (n_25), .Y (n_1015_BAR));
  NOR2X2 g4037__1881(.A (addr[1]), .B (addr[2]), .Y (n_27));
  NOR2BX2 g4038__5115(.AN (addr[1]), .B (addr[2]), .Y (n_26));
  NOR2BX2 g4039__7482(.AN (addr[2]), .B (addr[1]), .Y (n_25));
  AND2X1 g4040__4733(.A (addr[2]), .B (addr[1]), .Y (n_24));
  INVX2 g4041(.A (addr[0]), .Y (n_23));
  BUFX2 drc_bufs(.A (n_173), .Y (data_out[13]));
  BUFX2 drc_bufs4049(.A (n_172), .Y (data_out[12]));
  BUFX2 drc_bufs4058(.A (n_182), .Y (data_out[7]));
  BUFX2 drc_bufs4059(.A (n_178), .Y (data_out[10]));
  BUFX2 drc_bufs4060(.A (n_177), .Y (data_out[1]));
  BUFX2 drc_bufs4061(.A (n_184), .Y (data_out[9]));
  BUFX2 drc_bufs4062(.A (n_176), .Y (data_out[0]));
  BUFX2 drc_bufs4063(.A (n_181), .Y (data_out[6]));
  BUFX2 drc_bufs4064(.A (n_175), .Y (data_out[15]));
  BUFX2 drc_bufs4065(.A (n_183), .Y (data_out[8]));
  BUFX2 drc_bufs4066(.A (n_174), .Y (data_out[14]));
  BUFX2 drc_bufs4067(.A (n_180), .Y (data_out[5]));
  BUFX2 drc_bufs4068(.A (n_185), .Y (data_out[3]));
  BUFX2 drc_bufs4069(.A (n_179), .Y (data_out[4]));
  BUFX2 drc_bufs4070(.A (n_171), .Y (data_out[2]));
  BUFX2 drc_bufs4087(.A (n_53), .Y (n_22));
  BUFX2 drc_bufs4088(.A (n_81), .Y (n_21));
  BUFX2 drc_bufs4089(.A (n_144), .Y (n_20));
  BUFX2 drc_bufs4090(.A (n_28), .Y (n_19));
  BUFX2 drc_bufs4091(.A (n_44), .Y (n_18));
  BUFX2 drc_bufs4092(.A (n_70), .Y (n_17));
  BUFX2 drc_bufs4093(.A (n_110), .Y (n_16));
  BUFX2 drc_bufs4094(.A (n_98), .Y (n_15));
  BUFX2 drc_bufs4095(.A (n_62), .Y (n_14));
  BUFX2 drc_bufs4096(.A (n_87), .Y (n_13));
  BUFX2 drc_bufs4097(.A (n_118), .Y (n_12));
  EDFFHQX1 \mem_data_reg[0][0] (.CK (clk), .D (data_in[0]), .E (n_8),
       .Q (\mem_data[0] [0]));
  EDFFHQX1 \mem_data_reg[0][1] (.CK (clk), .D (data_in[1]), .E (n_8),
       .Q (\mem_data[0] [1]));
  EDFFHQX1 \mem_data_reg[0][2] (.CK (clk), .D (data_in[2]), .E (n_8),
       .Q (\mem_data[0] [2]));
  EDFFHQX1 \mem_data_reg[0][3] (.CK (clk), .D (data_in[3]), .E (n_8),
       .Q (\mem_data[0] [3]));
  EDFFHQX1 \mem_data_reg[0][4] (.CK (clk), .D (data_in[4]), .E (n_8),
       .Q (\mem_data[0] [4]));
  EDFFHQX1 \mem_data_reg[0][5] (.CK (clk), .D (data_in[5]), .E (n_8),
       .Q (\mem_data[0] [5]));
  EDFFHQX1 \mem_data_reg[0][6] (.CK (clk), .D (data_in[6]), .E (n_8),
       .Q (\mem_data[0] [6]));
  EDFFHQX1 \mem_data_reg[0][7] (.CK (clk), .D (data_in[7]), .E (n_8),
       .Q (\mem_data[0] [7]));
  EDFFHQX1 \mem_data_reg[0][8] (.CK (clk), .D (data_in[8]), .E (n_8),
       .Q (\mem_data[0] [8]));
  EDFFHQX1 \mem_data_reg[0][9] (.CK (clk), .D (data_in[9]), .E (n_8),
       .Q (\mem_data[0] [9]));
  EDFFHQX1 \mem_data_reg[0][10] (.CK (clk), .D (data_in[10]), .E (n_8),
       .Q (\mem_data[0] [10]));
  EDFFHQX1 \mem_data_reg[0][11] (.CK (clk), .D (data_in[11]), .E (n_8),
       .Q (\mem_data[0] [11]));
  EDFFHQX1 \mem_data_reg[0][12] (.CK (clk), .D (data_in[12]), .E (n_8),
       .Q (\mem_data[0] [12]));
  EDFFHQX1 \mem_data_reg[0][13] (.CK (clk), .D (data_in[13]), .E (n_8),
       .Q (\mem_data[0] [13]));
  EDFFHQX1 \mem_data_reg[0][14] (.CK (clk), .D (data_in[14]), .E (n_8),
       .Q (\mem_data[0] [14]));
  EDFFHQX1 \mem_data_reg[0][15] (.CK (clk), .D (data_in[15]), .E (n_8),
       .Q (\mem_data[0] [15]));
  EDFFHQX1 \mem_data_reg[0][16] (.CK (clk), .D (data_in[16]), .E (n_8),
       .Q (\mem_data[0] [16]));
  EDFFHQX1 \mem_data_reg[0][17] (.CK (clk), .D (data_in[17]), .E (n_8),
       .Q (\mem_data[0] [17]));
  EDFFHQX1 \mem_data_reg[0][18] (.CK (clk), .D (data_in[18]), .E (n_8),
       .Q (\mem_data[0] [18]));
  EDFFHQX1 \mem_data_reg[0][19] (.CK (clk), .D (data_in[19]), .E (n_8),
       .Q (\mem_data[0] [19]));
  EDFFHQX1 \mem_data_reg[0][20] (.CK (clk), .D (data_in[20]), .E (n_8),
       .Q (\mem_data[0] [20]));
  EDFFHQX1 \mem_data_reg[0][21] (.CK (clk), .D (data_in[21]), .E (n_8),
       .Q (\mem_data[0] [21]));
  EDFFHQX1 \mem_data_reg[0][22] (.CK (clk), .D (data_in[22]), .E (n_8),
       .Q (\mem_data[0] [22]));
  EDFFHQX1 \mem_data_reg[0][23] (.CK (clk), .D (data_in[23]), .E (n_8),
       .Q (\mem_data[0] [23]));
  EDFFHQX1 \mem_data_reg[0][24] (.CK (clk), .D (data_in[24]), .E (n_8),
       .Q (\mem_data[0] [24]));
  EDFFHQX1 \mem_data_reg[0][25] (.CK (clk), .D (data_in[25]), .E (n_8),
       .Q (\mem_data[0] [25]));
  EDFFHQX1 \mem_data_reg[0][26] (.CK (clk), .D (data_in[26]), .E (n_8),
       .Q (\mem_data[0] [26]));
  EDFFHQX1 \mem_data_reg[0][27] (.CK (clk), .D (data_in[27]), .E (n_8),
       .Q (\mem_data[0] [27]));
  EDFFHQX1 \mem_data_reg[0][28] (.CK (clk), .D (data_in[28]), .E (n_8),
       .Q (\mem_data[0] [28]));
  EDFFHQX1 \mem_data_reg[0][29] (.CK (clk), .D (data_in[29]), .E (n_8),
       .Q (\mem_data[0] [29]));
  EDFFHQX1 \mem_data_reg[0][30] (.CK (clk), .D (data_in[30]), .E (n_8),
       .Q (\mem_data[0] [30]));
  EDFFHQX1 \mem_data_reg[0][31] (.CK (clk), .D (data_in[31]), .E (n_8),
       .Q (\mem_data[0] [31]));
  EDFFHQX1 \mem_data_reg[1][0] (.CK (clk), .D (data_in[0]), .E (n_7),
       .Q (\mem_data[1] [0]));
  EDFFHQX1 \mem_data_reg[1][1] (.CK (clk), .D (data_in[1]), .E (n_7),
       .Q (\mem_data[1] [1]));
  EDFFHQX1 \mem_data_reg[1][2] (.CK (clk), .D (data_in[2]), .E (n_7),
       .Q (\mem_data[1] [2]));
  EDFFHQX1 \mem_data_reg[1][3] (.CK (clk), .D (data_in[3]), .E (n_7),
       .Q (\mem_data[1] [3]));
  EDFFHQX1 \mem_data_reg[1][4] (.CK (clk), .D (data_in[4]), .E (n_7),
       .Q (\mem_data[1] [4]));
  EDFFHQX1 \mem_data_reg[1][5] (.CK (clk), .D (data_in[5]), .E (n_7),
       .Q (\mem_data[1] [5]));
  EDFFHQX1 \mem_data_reg[1][6] (.CK (clk), .D (data_in[6]), .E (n_7),
       .Q (\mem_data[1] [6]));
  EDFFHQX1 \mem_data_reg[1][7] (.CK (clk), .D (data_in[7]), .E (n_7),
       .Q (\mem_data[1] [7]));
  EDFFHQX1 \mem_data_reg[1][8] (.CK (clk), .D (data_in[8]), .E (n_7),
       .Q (\mem_data[1] [8]));
  EDFFHQX1 \mem_data_reg[1][9] (.CK (clk), .D (data_in[9]), .E (n_7),
       .Q (\mem_data[1] [9]));
  EDFFHQX1 \mem_data_reg[1][10] (.CK (clk), .D (data_in[10]), .E (n_7),
       .Q (\mem_data[1] [10]));
  EDFFHQX1 \mem_data_reg[1][11] (.CK (clk), .D (data_in[11]), .E (n_7),
       .Q (\mem_data[1] [11]));
  EDFFHQX1 \mem_data_reg[1][12] (.CK (clk), .D (data_in[12]), .E (n_7),
       .Q (\mem_data[1] [12]));
  EDFFHQX1 \mem_data_reg[1][13] (.CK (clk), .D (data_in[13]), .E (n_7),
       .Q (\mem_data[1] [13]));
  EDFFHQX1 \mem_data_reg[1][14] (.CK (clk), .D (data_in[14]), .E (n_7),
       .Q (\mem_data[1] [14]));
  EDFFHQX1 \mem_data_reg[1][15] (.CK (clk), .D (data_in[15]), .E (n_7),
       .Q (\mem_data[1] [15]));
  EDFFHQX1 \mem_data_reg[1][16] (.CK (clk), .D (data_in[16]), .E (n_7),
       .Q (\mem_data[1] [16]));
  EDFFHQX1 \mem_data_reg[1][17] (.CK (clk), .D (data_in[17]), .E (n_7),
       .Q (\mem_data[1] [17]));
  EDFFHQX1 \mem_data_reg[1][18] (.CK (clk), .D (data_in[18]), .E (n_7),
       .Q (\mem_data[1] [18]));
  EDFFHQX1 \mem_data_reg[1][19] (.CK (clk), .D (data_in[19]), .E (n_7),
       .Q (\mem_data[1] [19]));
  EDFFHQX1 \mem_data_reg[1][20] (.CK (clk), .D (data_in[20]), .E (n_7),
       .Q (\mem_data[1] [20]));
  EDFFHQX1 \mem_data_reg[1][21] (.CK (clk), .D (data_in[21]), .E (n_7),
       .Q (\mem_data[1] [21]));
  EDFFHQX1 \mem_data_reg[1][22] (.CK (clk), .D (data_in[22]), .E (n_7),
       .Q (\mem_data[1] [22]));
  EDFFHQX1 \mem_data_reg[1][23] (.CK (clk), .D (data_in[23]), .E (n_7),
       .Q (\mem_data[1] [23]));
  EDFFHQX1 \mem_data_reg[1][24] (.CK (clk), .D (data_in[24]), .E (n_7),
       .Q (\mem_data[1] [24]));
  EDFFHQX1 \mem_data_reg[1][25] (.CK (clk), .D (data_in[25]), .E (n_7),
       .Q (\mem_data[1] [25]));
  EDFFHQX1 \mem_data_reg[1][26] (.CK (clk), .D (data_in[26]), .E (n_7),
       .Q (\mem_data[1] [26]));
  EDFFHQX1 \mem_data_reg[1][27] (.CK (clk), .D (data_in[27]), .E (n_7),
       .Q (\mem_data[1] [27]));
  EDFFHQX1 \mem_data_reg[1][28] (.CK (clk), .D (data_in[28]), .E (n_7),
       .Q (\mem_data[1] [28]));
  EDFFHQX1 \mem_data_reg[1][29] (.CK (clk), .D (data_in[29]), .E (n_7),
       .Q (\mem_data[1] [29]));
  EDFFHQX1 \mem_data_reg[1][30] (.CK (clk), .D (data_in[30]), .E (n_7),
       .Q (\mem_data[1] [30]));
  EDFFHQX1 \mem_data_reg[1][31] (.CK (clk), .D (data_in[31]), .E (n_7),
       .Q (\mem_data[1] [31]));
  EDFFHQX1 \mem_data_reg[2][0] (.CK (clk), .D (data_in[0]), .E (n_4),
       .Q (\mem_data[2] [0]));
  EDFFHQX1 \mem_data_reg[2][1] (.CK (clk), .D (data_in[1]), .E (n_4),
       .Q (\mem_data[2] [1]));
  EDFFHQX1 \mem_data_reg[2][2] (.CK (clk), .D (data_in[2]), .E (n_4),
       .Q (\mem_data[2] [2]));
  EDFFHQX1 \mem_data_reg[2][3] (.CK (clk), .D (data_in[3]), .E (n_4),
       .Q (\mem_data[2] [3]));
  EDFFHQX1 \mem_data_reg[2][4] (.CK (clk), .D (data_in[4]), .E (n_4),
       .Q (\mem_data[2] [4]));
  EDFFHQX1 \mem_data_reg[2][5] (.CK (clk), .D (data_in[5]), .E (n_4),
       .Q (\mem_data[2] [5]));
  EDFFHQX1 \mem_data_reg[2][6] (.CK (clk), .D (data_in[6]), .E (n_4),
       .Q (\mem_data[2] [6]));
  EDFFHQX1 \mem_data_reg[2][7] (.CK (clk), .D (data_in[7]), .E (n_4),
       .Q (\mem_data[2] [7]));
  EDFFHQX1 \mem_data_reg[2][8] (.CK (clk), .D (data_in[8]), .E (n_4),
       .Q (\mem_data[2] [8]));
  EDFFHQX1 \mem_data_reg[2][9] (.CK (clk), .D (data_in[9]), .E (n_4),
       .Q (\mem_data[2] [9]));
  EDFFHQX1 \mem_data_reg[2][10] (.CK (clk), .D (data_in[10]), .E (n_4),
       .Q (\mem_data[2] [10]));
  EDFFHQX1 \mem_data_reg[2][11] (.CK (clk), .D (data_in[11]), .E (n_4),
       .Q (\mem_data[2] [11]));
  EDFFHQX1 \mem_data_reg[2][12] (.CK (clk), .D (data_in[12]), .E (n_4),
       .Q (\mem_data[2] [12]));
  EDFFHQX1 \mem_data_reg[2][13] (.CK (clk), .D (data_in[13]), .E (n_4),
       .Q (\mem_data[2] [13]));
  EDFFHQX1 \mem_data_reg[2][14] (.CK (clk), .D (data_in[14]), .E (n_4),
       .Q (\mem_data[2] [14]));
  EDFFHQX1 \mem_data_reg[2][15] (.CK (clk), .D (data_in[15]), .E (n_4),
       .Q (\mem_data[2] [15]));
  EDFFHQX1 \mem_data_reg[2][16] (.CK (clk), .D (data_in[16]), .E (n_4),
       .Q (\mem_data[2] [16]));
  EDFFHQX1 \mem_data_reg[2][17] (.CK (clk), .D (data_in[17]), .E (n_4),
       .Q (\mem_data[2] [17]));
  EDFFHQX1 \mem_data_reg[2][18] (.CK (clk), .D (data_in[18]), .E (n_4),
       .Q (\mem_data[2] [18]));
  EDFFHQX1 \mem_data_reg[2][19] (.CK (clk), .D (data_in[19]), .E (n_4),
       .Q (\mem_data[2] [19]));
  EDFFHQX1 \mem_data_reg[2][20] (.CK (clk), .D (data_in[20]), .E (n_4),
       .Q (\mem_data[2] [20]));
  EDFFHQX1 \mem_data_reg[2][21] (.CK (clk), .D (data_in[21]), .E (n_4),
       .Q (\mem_data[2] [21]));
  EDFFHQX1 \mem_data_reg[2][22] (.CK (clk), .D (data_in[22]), .E (n_4),
       .Q (\mem_data[2] [22]));
  EDFFHQX1 \mem_data_reg[2][23] (.CK (clk), .D (data_in[23]), .E (n_4),
       .Q (\mem_data[2] [23]));
  EDFFHQX1 \mem_data_reg[2][24] (.CK (clk), .D (data_in[24]), .E (n_4),
       .Q (\mem_data[2] [24]));
  EDFFHQX1 \mem_data_reg[2][25] (.CK (clk), .D (data_in[25]), .E (n_4),
       .Q (\mem_data[2] [25]));
  EDFFHQX1 \mem_data_reg[2][26] (.CK (clk), .D (data_in[26]), .E (n_4),
       .Q (\mem_data[2] [26]));
  EDFFHQX1 \mem_data_reg[2][27] (.CK (clk), .D (data_in[27]), .E (n_4),
       .Q (\mem_data[2] [27]));
  EDFFHQX1 \mem_data_reg[2][28] (.CK (clk), .D (data_in[28]), .E (n_4),
       .Q (\mem_data[2] [28]));
  EDFFHQX1 \mem_data_reg[2][29] (.CK (clk), .D (data_in[29]), .E (n_4),
       .Q (\mem_data[2] [29]));
  EDFFHQX1 \mem_data_reg[2][30] (.CK (clk), .D (data_in[30]), .E (n_4),
       .Q (\mem_data[2] [30]));
  EDFFHQX1 \mem_data_reg[2][31] (.CK (clk), .D (data_in[31]), .E (n_4),
       .Q (\mem_data[2] [31]));
  EDFFHQX1 \mem_data_reg[3][0] (.CK (clk), .D (data_in[0]), .E (n_11),
       .Q (\mem_data[3] [0]));
  EDFFHQX1 \mem_data_reg[3][1] (.CK (clk), .D (data_in[1]), .E (n_11),
       .Q (\mem_data[3] [1]));
  EDFFHQX1 \mem_data_reg[3][2] (.CK (clk), .D (data_in[2]), .E (n_11),
       .Q (\mem_data[3] [2]));
  EDFFHQX1 \mem_data_reg[3][3] (.CK (clk), .D (data_in[3]), .E (n_11),
       .Q (\mem_data[3] [3]));
  EDFFHQX1 \mem_data_reg[3][4] (.CK (clk), .D (data_in[4]), .E (n_11),
       .Q (\mem_data[3] [4]));
  EDFFHQX1 \mem_data_reg[3][5] (.CK (clk), .D (data_in[5]), .E (n_11),
       .Q (\mem_data[3] [5]));
  EDFFHQX1 \mem_data_reg[3][6] (.CK (clk), .D (data_in[6]), .E (n_11),
       .Q (\mem_data[3] [6]));
  EDFFHQX1 \mem_data_reg[3][7] (.CK (clk), .D (data_in[7]), .E (n_11),
       .Q (\mem_data[3] [7]));
  EDFFHQX1 \mem_data_reg[3][8] (.CK (clk), .D (data_in[8]), .E (n_11),
       .Q (\mem_data[3] [8]));
  EDFFHQX1 \mem_data_reg[3][9] (.CK (clk), .D (data_in[9]), .E (n_11),
       .Q (\mem_data[3] [9]));
  EDFFHQX1 \mem_data_reg[3][10] (.CK (clk), .D (data_in[10]), .E
       (n_11), .Q (\mem_data[3] [10]));
  EDFFHQX1 \mem_data_reg[3][11] (.CK (clk), .D (data_in[11]), .E
       (n_11), .Q (\mem_data[3] [11]));
  EDFFHQX1 \mem_data_reg[3][12] (.CK (clk), .D (data_in[12]), .E
       (n_11), .Q (\mem_data[3] [12]));
  EDFFHQX1 \mem_data_reg[3][13] (.CK (clk), .D (data_in[13]), .E
       (n_11), .Q (\mem_data[3] [13]));
  EDFFHQX1 \mem_data_reg[3][14] (.CK (clk), .D (data_in[14]), .E
       (n_11), .Q (\mem_data[3] [14]));
  EDFFHQX1 \mem_data_reg[3][15] (.CK (clk), .D (data_in[15]), .E
       (n_11), .Q (\mem_data[3] [15]));
  EDFFHQX1 \mem_data_reg[3][16] (.CK (clk), .D (data_in[16]), .E
       (n_11), .Q (\mem_data[3] [16]));
  EDFFHQX1 \mem_data_reg[3][17] (.CK (clk), .D (data_in[17]), .E
       (n_11), .Q (\mem_data[3] [17]));
  EDFFHQX1 \mem_data_reg[3][18] (.CK (clk), .D (data_in[18]), .E
       (n_11), .Q (\mem_data[3] [18]));
  EDFFHQX1 \mem_data_reg[3][19] (.CK (clk), .D (data_in[19]), .E
       (n_11), .Q (\mem_data[3] [19]));
  EDFFHQX1 \mem_data_reg[3][20] (.CK (clk), .D (data_in[20]), .E
       (n_11), .Q (\mem_data[3] [20]));
  EDFFHQX1 \mem_data_reg[3][21] (.CK (clk), .D (data_in[21]), .E
       (n_11), .Q (\mem_data[3] [21]));
  EDFFHQX1 \mem_data_reg[3][22] (.CK (clk), .D (data_in[22]), .E
       (n_11), .Q (\mem_data[3] [22]));
  EDFFHQX1 \mem_data_reg[3][23] (.CK (clk), .D (data_in[23]), .E
       (n_11), .Q (\mem_data[3] [23]));
  EDFFHQX1 \mem_data_reg[3][24] (.CK (clk), .D (data_in[24]), .E
       (n_11), .Q (\mem_data[3] [24]));
  EDFFHQX1 \mem_data_reg[3][25] (.CK (clk), .D (data_in[25]), .E
       (n_11), .Q (\mem_data[3] [25]));
  EDFFHQX1 \mem_data_reg[3][26] (.CK (clk), .D (data_in[26]), .E
       (n_11), .Q (\mem_data[3] [26]));
  EDFFHQX1 \mem_data_reg[3][27] (.CK (clk), .D (data_in[27]), .E
       (n_11), .Q (\mem_data[3] [27]));
  EDFFHQX1 \mem_data_reg[3][28] (.CK (clk), .D (data_in[28]), .E
       (n_11), .Q (\mem_data[3] [28]));
  EDFFHQX1 \mem_data_reg[3][29] (.CK (clk), .D (data_in[29]), .E
       (n_11), .Q (\mem_data[3] [29]));
  EDFFHQX1 \mem_data_reg[3][30] (.CK (clk), .D (data_in[30]), .E
       (n_11), .Q (\mem_data[3] [30]));
  EDFFHQX1 \mem_data_reg[3][31] (.CK (clk), .D (data_in[31]), .E
       (n_11), .Q (\mem_data[3] [31]));
  EDFFHQX1 \mem_data_reg[4][0] (.CK (clk), .D (data_in[0]), .E (n_10),
       .Q (\mem_data[4] [0]));
  EDFFHQX1 \mem_data_reg[4][1] (.CK (clk), .D (data_in[1]), .E (n_10),
       .Q (\mem_data[4] [1]));
  EDFFHQX1 \mem_data_reg[4][2] (.CK (clk), .D (data_in[2]), .E (n_10),
       .Q (\mem_data[4] [2]));
  EDFFHQX1 \mem_data_reg[4][3] (.CK (clk), .D (data_in[3]), .E (n_10),
       .Q (\mem_data[4] [3]));
  EDFFHQX1 \mem_data_reg[4][4] (.CK (clk), .D (data_in[4]), .E (n_10),
       .Q (\mem_data[4] [4]));
  EDFFHQX1 \mem_data_reg[4][5] (.CK (clk), .D (data_in[5]), .E (n_10),
       .Q (\mem_data[4] [5]));
  EDFFHQX1 \mem_data_reg[4][6] (.CK (clk), .D (data_in[6]), .E (n_10),
       .Q (\mem_data[4] [6]));
  EDFFHQX1 \mem_data_reg[4][7] (.CK (clk), .D (data_in[7]), .E (n_10),
       .Q (\mem_data[4] [7]));
  EDFFHQX1 \mem_data_reg[4][8] (.CK (clk), .D (data_in[8]), .E (n_10),
       .Q (\mem_data[4] [8]));
  EDFFHQX1 \mem_data_reg[4][9] (.CK (clk), .D (data_in[9]), .E (n_10),
       .Q (\mem_data[4] [9]));
  EDFFHQX1 \mem_data_reg[4][10] (.CK (clk), .D (data_in[10]), .E
       (n_10), .Q (\mem_data[4] [10]));
  EDFFHQX1 \mem_data_reg[4][11] (.CK (clk), .D (data_in[11]), .E
       (n_10), .Q (\mem_data[4] [11]));
  EDFFHQX1 \mem_data_reg[4][12] (.CK (clk), .D (data_in[12]), .E
       (n_10), .Q (\mem_data[4] [12]));
  EDFFHQX1 \mem_data_reg[4][13] (.CK (clk), .D (data_in[13]), .E
       (n_10), .Q (\mem_data[4] [13]));
  EDFFHQX1 \mem_data_reg[4][14] (.CK (clk), .D (data_in[14]), .E
       (n_10), .Q (\mem_data[4] [14]));
  EDFFHQX1 \mem_data_reg[4][15] (.CK (clk), .D (data_in[15]), .E
       (n_10), .Q (\mem_data[4] [15]));
  EDFFHQX1 \mem_data_reg[4][16] (.CK (clk), .D (data_in[16]), .E
       (n_10), .Q (\mem_data[4] [16]));
  EDFFHQX1 \mem_data_reg[4][17] (.CK (clk), .D (data_in[17]), .E
       (n_10), .Q (\mem_data[4] [17]));
  EDFFHQX1 \mem_data_reg[4][18] (.CK (clk), .D (data_in[18]), .E
       (n_10), .Q (\mem_data[4] [18]));
  EDFFHQX1 \mem_data_reg[4][19] (.CK (clk), .D (data_in[19]), .E
       (n_10), .Q (\mem_data[4] [19]));
  EDFFHQX1 \mem_data_reg[4][20] (.CK (clk), .D (data_in[20]), .E
       (n_10), .Q (\mem_data[4] [20]));
  EDFFHQX1 \mem_data_reg[4][21] (.CK (clk), .D (data_in[21]), .E
       (n_10), .Q (\mem_data[4] [21]));
  EDFFHQX1 \mem_data_reg[4][22] (.CK (clk), .D (data_in[22]), .E
       (n_10), .Q (\mem_data[4] [22]));
  EDFFHQX1 \mem_data_reg[4][23] (.CK (clk), .D (data_in[23]), .E
       (n_10), .Q (\mem_data[4] [23]));
  EDFFHQX1 \mem_data_reg[4][24] (.CK (clk), .D (data_in[24]), .E
       (n_10), .Q (\mem_data[4] [24]));
  EDFFHQX1 \mem_data_reg[4][25] (.CK (clk), .D (data_in[25]), .E
       (n_10), .Q (\mem_data[4] [25]));
  EDFFHQX1 \mem_data_reg[4][26] (.CK (clk), .D (data_in[26]), .E
       (n_10), .Q (\mem_data[4] [26]));
  EDFFHQX1 \mem_data_reg[4][27] (.CK (clk), .D (data_in[27]), .E
       (n_10), .Q (\mem_data[4] [27]));
  EDFFHQX1 \mem_data_reg[4][28] (.CK (clk), .D (data_in[28]), .E
       (n_10), .Q (\mem_data[4] [28]));
  EDFFHQX1 \mem_data_reg[4][29] (.CK (clk), .D (data_in[29]), .E
       (n_10), .Q (\mem_data[4] [29]));
  EDFFHQX1 \mem_data_reg[4][30] (.CK (clk), .D (data_in[30]), .E
       (n_10), .Q (\mem_data[4] [30]));
  EDFFHQX1 \mem_data_reg[4][31] (.CK (clk), .D (data_in[31]), .E
       (n_10), .Q (\mem_data[4] [31]));
  EDFFHQX1 \mem_data_reg[5][0] (.CK (clk), .D (data_in[0]), .E (n_6),
       .Q (\mem_data[5] [0]));
  EDFFHQX1 \mem_data_reg[5][1] (.CK (clk), .D (data_in[1]), .E (n_6),
       .Q (\mem_data[5] [1]));
  EDFFHQX1 \mem_data_reg[5][2] (.CK (clk), .D (data_in[2]), .E (n_6),
       .Q (\mem_data[5] [2]));
  EDFFHQX1 \mem_data_reg[5][3] (.CK (clk), .D (data_in[3]), .E (n_6),
       .Q (\mem_data[5] [3]));
  EDFFHQX1 \mem_data_reg[5][4] (.CK (clk), .D (data_in[4]), .E (n_6),
       .Q (\mem_data[5] [4]));
  EDFFHQX1 \mem_data_reg[5][5] (.CK (clk), .D (data_in[5]), .E (n_6),
       .Q (\mem_data[5] [5]));
  EDFFHQX1 \mem_data_reg[5][6] (.CK (clk), .D (data_in[6]), .E (n_6),
       .Q (\mem_data[5] [6]));
  EDFFHQX1 \mem_data_reg[5][7] (.CK (clk), .D (data_in[7]), .E (n_6),
       .Q (\mem_data[5] [7]));
  EDFFHQX1 \mem_data_reg[5][8] (.CK (clk), .D (data_in[8]), .E (n_6),
       .Q (\mem_data[5] [8]));
  EDFFHQX1 \mem_data_reg[5][9] (.CK (clk), .D (data_in[9]), .E (n_6),
       .Q (\mem_data[5] [9]));
  EDFFHQX1 \mem_data_reg[5][10] (.CK (clk), .D (data_in[10]), .E (n_6),
       .Q (\mem_data[5] [10]));
  EDFFHQX1 \mem_data_reg[5][11] (.CK (clk), .D (data_in[11]), .E (n_6),
       .Q (\mem_data[5] [11]));
  EDFFHQX1 \mem_data_reg[5][12] (.CK (clk), .D (data_in[12]), .E (n_6),
       .Q (\mem_data[5] [12]));
  EDFFHQX1 \mem_data_reg[5][13] (.CK (clk), .D (data_in[13]), .E (n_6),
       .Q (\mem_data[5] [13]));
  EDFFHQX1 \mem_data_reg[5][14] (.CK (clk), .D (data_in[14]), .E (n_6),
       .Q (\mem_data[5] [14]));
  EDFFHQX1 \mem_data_reg[5][15] (.CK (clk), .D (data_in[15]), .E (n_6),
       .Q (\mem_data[5] [15]));
  EDFFHQX1 \mem_data_reg[5][16] (.CK (clk), .D (data_in[16]), .E (n_6),
       .Q (\mem_data[5] [16]));
  EDFFHQX1 \mem_data_reg[5][17] (.CK (clk), .D (data_in[17]), .E (n_6),
       .Q (\mem_data[5] [17]));
  EDFFHQX1 \mem_data_reg[5][18] (.CK (clk), .D (data_in[18]), .E (n_6),
       .Q (\mem_data[5] [18]));
  EDFFHQX1 \mem_data_reg[5][19] (.CK (clk), .D (data_in[19]), .E (n_6),
       .Q (\mem_data[5] [19]));
  EDFFHQX1 \mem_data_reg[5][20] (.CK (clk), .D (data_in[20]), .E (n_6),
       .Q (\mem_data[5] [20]));
  EDFFHQX1 \mem_data_reg[5][21] (.CK (clk), .D (data_in[21]), .E (n_6),
       .Q (\mem_data[5] [21]));
  EDFFHQX1 \mem_data_reg[5][22] (.CK (clk), .D (data_in[22]), .E (n_6),
       .Q (\mem_data[5] [22]));
  EDFFHQX1 \mem_data_reg[5][23] (.CK (clk), .D (data_in[23]), .E (n_6),
       .Q (\mem_data[5] [23]));
  EDFFHQX1 \mem_data_reg[5][24] (.CK (clk), .D (data_in[24]), .E (n_6),
       .Q (\mem_data[5] [24]));
  EDFFHQX1 \mem_data_reg[5][25] (.CK (clk), .D (data_in[25]), .E (n_6),
       .Q (\mem_data[5] [25]));
  EDFFHQX1 \mem_data_reg[5][26] (.CK (clk), .D (data_in[26]), .E (n_6),
       .Q (\mem_data[5] [26]));
  EDFFHQX1 \mem_data_reg[5][27] (.CK (clk), .D (data_in[27]), .E (n_6),
       .Q (\mem_data[5] [27]));
  EDFFHQX1 \mem_data_reg[5][28] (.CK (clk), .D (data_in[28]), .E (n_6),
       .Q (\mem_data[5] [28]));
  EDFFHQX1 \mem_data_reg[5][29] (.CK (clk), .D (data_in[29]), .E (n_6),
       .Q (\mem_data[5] [29]));
  EDFFHQX1 \mem_data_reg[5][30] (.CK (clk), .D (data_in[30]), .E (n_6),
       .Q (\mem_data[5] [30]));
  EDFFHQX1 \mem_data_reg[5][31] (.CK (clk), .D (data_in[31]), .E (n_6),
       .Q (\mem_data[5] [31]));
  EDFFHQX1 \mem_data_reg[6][0] (.CK (clk), .D (data_in[0]), .E (n_9),
       .Q (\mem_data[6] [0]));
  EDFFHQX1 \mem_data_reg[6][1] (.CK (clk), .D (data_in[1]), .E (n_9),
       .Q (\mem_data[6] [1]));
  EDFFHQX1 \mem_data_reg[6][2] (.CK (clk), .D (data_in[2]), .E (n_9),
       .Q (\mem_data[6] [2]));
  EDFFHQX1 \mem_data_reg[6][3] (.CK (clk), .D (data_in[3]), .E (n_9),
       .Q (\mem_data[6] [3]));
  EDFFHQX1 \mem_data_reg[6][4] (.CK (clk), .D (data_in[4]), .E (n_9),
       .Q (\mem_data[6] [4]));
  EDFFHQX1 \mem_data_reg[6][5] (.CK (clk), .D (data_in[5]), .E (n_9),
       .Q (\mem_data[6] [5]));
  EDFFHQX1 \mem_data_reg[6][6] (.CK (clk), .D (data_in[6]), .E (n_9),
       .Q (\mem_data[6] [6]));
  EDFFHQX1 \mem_data_reg[6][7] (.CK (clk), .D (data_in[7]), .E (n_9),
       .Q (\mem_data[6] [7]));
  EDFFHQX1 \mem_data_reg[6][8] (.CK (clk), .D (data_in[8]), .E (n_9),
       .Q (\mem_data[6] [8]));
  EDFFHQX1 \mem_data_reg[6][9] (.CK (clk), .D (data_in[9]), .E (n_9),
       .Q (\mem_data[6] [9]));
  EDFFHQX1 \mem_data_reg[6][10] (.CK (clk), .D (data_in[10]), .E (n_9),
       .Q (\mem_data[6] [10]));
  EDFFHQX1 \mem_data_reg[6][11] (.CK (clk), .D (data_in[11]), .E (n_9),
       .Q (\mem_data[6] [11]));
  EDFFHQX1 \mem_data_reg[6][12] (.CK (clk), .D (data_in[12]), .E (n_9),
       .Q (\mem_data[6] [12]));
  EDFFHQX1 \mem_data_reg[6][13] (.CK (clk), .D (data_in[13]), .E (n_9),
       .Q (\mem_data[6] [13]));
  EDFFHQX1 \mem_data_reg[6][14] (.CK (clk), .D (data_in[14]), .E (n_9),
       .Q (\mem_data[6] [14]));
  EDFFHQX1 \mem_data_reg[6][15] (.CK (clk), .D (data_in[15]), .E (n_9),
       .Q (\mem_data[6] [15]));
  EDFFHQX1 \mem_data_reg[6][16] (.CK (clk), .D (data_in[16]), .E (n_9),
       .Q (\mem_data[6] [16]));
  EDFFHQX1 \mem_data_reg[6][17] (.CK (clk), .D (data_in[17]), .E (n_9),
       .Q (\mem_data[6] [17]));
  EDFFHQX1 \mem_data_reg[6][18] (.CK (clk), .D (data_in[18]), .E (n_9),
       .Q (\mem_data[6] [18]));
  EDFFHQX1 \mem_data_reg[6][19] (.CK (clk), .D (data_in[19]), .E (n_9),
       .Q (\mem_data[6] [19]));
  EDFFHQX1 \mem_data_reg[6][20] (.CK (clk), .D (data_in[20]), .E (n_9),
       .Q (\mem_data[6] [20]));
  EDFFHQX1 \mem_data_reg[6][21] (.CK (clk), .D (data_in[21]), .E (n_9),
       .Q (\mem_data[6] [21]));
  EDFFHQX1 \mem_data_reg[6][22] (.CK (clk), .D (data_in[22]), .E (n_9),
       .Q (\mem_data[6] [22]));
  EDFFHQX1 \mem_data_reg[6][23] (.CK (clk), .D (data_in[23]), .E (n_9),
       .Q (\mem_data[6] [23]));
  EDFFHQX1 \mem_data_reg[6][24] (.CK (clk), .D (data_in[24]), .E (n_9),
       .Q (\mem_data[6] [24]));
  EDFFHQX1 \mem_data_reg[6][25] (.CK (clk), .D (data_in[25]), .E (n_9),
       .Q (\mem_data[6] [25]));
  EDFFHQX1 \mem_data_reg[6][26] (.CK (clk), .D (data_in[26]), .E (n_9),
       .Q (\mem_data[6] [26]));
  EDFFHQX1 \mem_data_reg[6][27] (.CK (clk), .D (data_in[27]), .E (n_9),
       .Q (\mem_data[6] [27]));
  EDFFHQX1 \mem_data_reg[6][28] (.CK (clk), .D (data_in[28]), .E (n_9),
       .Q (\mem_data[6] [28]));
  EDFFHQX1 \mem_data_reg[6][29] (.CK (clk), .D (data_in[29]), .E (n_9),
       .Q (\mem_data[6] [29]));
  EDFFHQX1 \mem_data_reg[6][30] (.CK (clk), .D (data_in[30]), .E (n_9),
       .Q (\mem_data[6] [30]));
  EDFFHQX1 \mem_data_reg[6][31] (.CK (clk), .D (data_in[31]), .E (n_9),
       .Q (\mem_data[6] [31]));
  EDFFHQX1 \mem_data_reg[7][0] (.CK (clk), .D (data_in[0]), .E (n_5),
       .Q (\mem_data[7] [0]));
  EDFFHQX1 \mem_data_reg[7][1] (.CK (clk), .D (data_in[1]), .E (n_5),
       .Q (\mem_data[7] [1]));
  EDFFHQX1 \mem_data_reg[7][2] (.CK (clk), .D (data_in[2]), .E (n_5),
       .Q (\mem_data[7] [2]));
  EDFFHQX1 \mem_data_reg[7][3] (.CK (clk), .D (data_in[3]), .E (n_5),
       .Q (\mem_data[7] [3]));
  EDFFHQX1 \mem_data_reg[7][4] (.CK (clk), .D (data_in[4]), .E (n_5),
       .Q (\mem_data[7] [4]));
  EDFFHQX1 \mem_data_reg[7][5] (.CK (clk), .D (data_in[5]), .E (n_5),
       .Q (\mem_data[7] [5]));
  EDFFHQX1 \mem_data_reg[7][6] (.CK (clk), .D (data_in[6]), .E (n_5),
       .Q (\mem_data[7] [6]));
  EDFFHQX1 \mem_data_reg[7][7] (.CK (clk), .D (data_in[7]), .E (n_5),
       .Q (\mem_data[7] [7]));
  EDFFHQX1 \mem_data_reg[7][8] (.CK (clk), .D (data_in[8]), .E (n_5),
       .Q (\mem_data[7] [8]));
  EDFFHQX1 \mem_data_reg[7][9] (.CK (clk), .D (data_in[9]), .E (n_5),
       .Q (\mem_data[7] [9]));
  EDFFHQX1 \mem_data_reg[7][10] (.CK (clk), .D (data_in[10]), .E (n_5),
       .Q (\mem_data[7] [10]));
  EDFFHQX1 \mem_data_reg[7][11] (.CK (clk), .D (data_in[11]), .E (n_5),
       .Q (\mem_data[7] [11]));
  EDFFHQX1 \mem_data_reg[7][12] (.CK (clk), .D (data_in[12]), .E (n_5),
       .Q (\mem_data[7] [12]));
  EDFFHQX1 \mem_data_reg[7][13] (.CK (clk), .D (data_in[13]), .E (n_5),
       .Q (\mem_data[7] [13]));
  EDFFHQX1 \mem_data_reg[7][14] (.CK (clk), .D (data_in[14]), .E (n_5),
       .Q (\mem_data[7] [14]));
  EDFFHQX1 \mem_data_reg[7][15] (.CK (clk), .D (data_in[15]), .E (n_5),
       .Q (\mem_data[7] [15]));
  EDFFHQX1 \mem_data_reg[7][16] (.CK (clk), .D (data_in[16]), .E (n_5),
       .Q (\mem_data[7] [16]));
  EDFFHQX1 \mem_data_reg[7][17] (.CK (clk), .D (data_in[17]), .E (n_5),
       .Q (\mem_data[7] [17]));
  EDFFHQX1 \mem_data_reg[7][18] (.CK (clk), .D (data_in[18]), .E (n_5),
       .Q (\mem_data[7] [18]));
  EDFFHQX1 \mem_data_reg[7][19] (.CK (clk), .D (data_in[19]), .E (n_5),
       .Q (\mem_data[7] [19]));
  EDFFHQX1 \mem_data_reg[7][20] (.CK (clk), .D (data_in[20]), .E (n_5),
       .Q (\mem_data[7] [20]));
  EDFFHQX1 \mem_data_reg[7][21] (.CK (clk), .D (data_in[21]), .E (n_5),
       .Q (\mem_data[7] [21]));
  EDFFHQX1 \mem_data_reg[7][22] (.CK (clk), .D (data_in[22]), .E (n_5),
       .Q (\mem_data[7] [22]));
  EDFFHQX1 \mem_data_reg[7][23] (.CK (clk), .D (data_in[23]), .E (n_5),
       .Q (\mem_data[7] [23]));
  EDFFHQX1 \mem_data_reg[7][24] (.CK (clk), .D (data_in[24]), .E (n_5),
       .Q (\mem_data[7] [24]));
  EDFFHQX1 \mem_data_reg[7][25] (.CK (clk), .D (data_in[25]), .E (n_5),
       .Q (\mem_data[7] [25]));
  EDFFHQX1 \mem_data_reg[7][26] (.CK (clk), .D (data_in[26]), .E (n_5),
       .Q (\mem_data[7] [26]));
  EDFFHQX1 \mem_data_reg[7][27] (.CK (clk), .D (data_in[27]), .E (n_5),
       .Q (\mem_data[7] [27]));
  EDFFHQX1 \mem_data_reg[7][28] (.CK (clk), .D (data_in[28]), .E (n_5),
       .Q (\mem_data[7] [28]));
  EDFFHQX1 \mem_data_reg[7][29] (.CK (clk), .D (data_in[29]), .E (n_5),
       .Q (\mem_data[7] [29]));
  EDFFHQX1 \mem_data_reg[7][30] (.CK (clk), .D (data_in[30]), .E (n_5),
       .Q (\mem_data[7] [30]));
  EDFFHQX1 \mem_data_reg[7][31] (.CK (clk), .D (data_in[31]), .E (n_5),
       .Q (\mem_data[7] [31]));
  AND2X8 g1922__6161(.A (n_3), .B (n_992_BAR), .Y (n_11));
  AND2X8 g1923__9315(.A (n_3), .B (n_1015_BAR), .Y (n_10));
  AND2X8 g1924__9945(.A (n_3), .B (n_1013_BAR), .Y (n_9));
  AND2X8 g1925__2883(.A (n_3), .B (n_1021_BAR), .Y (n_8));
  AND2X8 g1926__2346(.A (n_3), .B (n_1009_BAR), .Y (n_7));
  AND2X8 g1927__1666(.A (n_3), .B (n_1017_BAR), .Y (n_6));
  AND2X8 g1928__7410(.A (n_3), .B (n_1005_BAR), .Y (n_5));
  AND2X8 g1929__6417(.A (n_3), .B (n_1019_BAR), .Y (n_4));
  AND2X2 g1930__5477(.A (n_1), .B (n_2), .Y (n_3));
  NOR3X1 g1931__2398(.A (addr[5]), .B (addr[6]), .C (n_0), .Y (n_2));
  NOR2XL g1932__5107(.A (addr[3]), .B (addr[4]), .Y (n_1));
  NAND2BX1 g1933__6260(.AN (addr[7]), .B (we), .Y (n_0));
endmodule

module tbec_decoder(in_word, decoded_word, error_code);
  input [31:0] in_word;
  output [15:0] decoded_word;
  output [1:0] error_code;
  wire [31:0] in_word;
  wire [15:0] decoded_word;
  wire [1:0] error_code;
  wire n_0, n_1, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_46, n_47, n_48;
  wire n_49, n_50, n_51, n_52, n_53, n_54, n_55, n_56;
  wire n_57, n_58, n_59, n_60, n_61, n_62, n_63, n_64;
  wire n_65, n_66, n_67, n_68, n_69, n_70, n_71, n_72;
  wire n_73, n_74, n_75, n_76, n_77, n_78, n_79, n_80;
  wire n_81, n_82, n_83, n_84, n_85, n_86, n_87, n_88;
  wire n_89, n_90, n_91, n_92, n_93, n_94, n_95, n_96;
  wire n_98, n_99;
  MX2X1 g2254__4319(.A (in_word[27]), .B (n_7), .S0 (n_99), .Y
       (decoded_word[14]));
  MX2X1 g2255__8428(.A (in_word[26]), .B (n_19), .S0 (n_99), .Y
       (decoded_word[10]));
  MX2X1 g2256__5526(.A (in_word[25]), .B (n_20), .S0 (n_99), .Y
       (decoded_word[6]));
  MX2X1 g2257__6783(.A (in_word[24]), .B (n_6), .S0 (n_99), .Y
       (decoded_word[2]));
  MX2X1 g2258__3680(.A (n_13), .B (in_word[18]), .S0 (n_98), .Y
       (decoded_word[8]));
  MX2X1 g2259__1617(.A (in_word[22]), .B (n_26), .S0 (error_code[1]),
       .Y (decoded_word[9]));
  MX2X1 g2260__2802(.A (in_word[21]), .B (n_25), .S0 (error_code[1]),
       .Y (decoded_word[5]));
  MX2X1 g2261__1705(.A (n_15), .B (in_word[17]), .S0 (n_98), .Y
       (decoded_word[4]));
  MX2X1 g2262__5122(.A (in_word[20]), .B (n_12), .S0 (error_code[1]),
       .Y (decoded_word[1]));
  MX2X1 g2263__8246(.A (n_14), .B (in_word[16]), .S0 (n_98), .Y
       (decoded_word[0]));
  MX2X1 g2264__7098(.A (in_word[23]), .B (n_27), .S0 (error_code[1]),
       .Y (decoded_word[13]));
  MX2X1 g2265__6131(.A (n_28), .B (in_word[19]), .S0 (n_98), .Y
       (decoded_word[12]));
  MX2X1 g2266__1881(.A (in_word[30]), .B (n_18), .S0 (n_1), .Y
       (decoded_word[11]));
  MX2X1 g2267__5115(.A (in_word[29]), .B (n_17), .S0 (n_1), .Y
       (decoded_word[7]));
  MX2X1 g2268__7482(.A (in_word[28]), .B (n_16), .S0 (n_1), .Y
       (decoded_word[3]));
  MX2X1 g2269__4733(.A (in_word[31]), .B (n_5), .S0 (n_1), .Y
       (decoded_word[15]));
  OR2X1 g2270__6161(.A (n_94), .B (n_1), .Y (n_99));
  OR3X1 g2272__9315(.A (n_88), .B (n_92), .C (n_93), .Y (n_98));
  AND2X4 g2273__9945(.A (n_96), .B (n_91), .Y (error_code[1]));
  OR2X1 g2275__2883(.A (n_0), .B (n_95), .Y (n_96));
  AOI21X1 g2276__2346(.A0 (n_87), .A1 (n_90), .B0 (n_88), .Y (n_95));
  NOR3X1 g2277__1666(.A (n_0), .B (n_89), .C (n_92), .Y (n_94));
  AOI21X1 g2278__7410(.A0 (n_86), .A1 (n_89), .B0 (n_0), .Y (n_93));
  INVX1 g2279(.A (n_92), .Y (n_91));
  MX2X1 g2280__6417(.A (n_53), .B (n_82), .S0 (n_85), .Y (n_92));
  OAI21X1 g2281__5477(.A0 (n_70), .A1 (n_56), .B0 (n_86), .Y (n_90));
  OAI2BB1X2 g2282__2398(.A0N (n_70), .A1N (n_56), .B0 (n_87), .Y
       (n_89));
  NOR2BX1 g2283__5107(.AN (n_83), .B (n_79), .Y (n_88));
  OR2X1 g2285__6260(.A (n_81), .B (n_84), .Y (n_87));
  NAND2X2 g2286__4319(.A (n_81), .B (n_84), .Y (n_86));
  AOI221X2 g2287__8428(.A0 (n_35), .A1 (n_37), .B0 (n_36), .B1 (n_47),
       .C0 (n_80), .Y (n_85));
  ADDHX1 g2289__5526(.A (n_76), .B (n_74), .CO (n_83), .S (n_84));
  OAI2BB1X1 g2290__6783(.A0N (n_65), .A1N (n_69), .B0 (n_77), .Y
       (n_82));
  NAND2X1 g2291__3680(.A (n_63), .B (n_78), .Y (n_80));
  XNOR2X1 g2292__1617(.A (n_68), .B (n_75), .Y (n_81));
  NOR2X1 g2293__2802(.A (n_68), .B (n_75), .Y (n_79));
  AOI22X1 g2294__1705(.A0 (n_66), .A1 (n_71), .B0 (n_38), .B1 (n_49),
       .Y (n_78));
  OR4X1 g2295__5122(.A (n_59), .B (n_57), .C (n_52), .D (n_53), .Y
       (n_77));
  OA21X1 g2296__8246(.A0 (in_word[11]), .A1 (n_32), .B0 (n_72), .Y
       (n_76));
  OAI2BB1X1 g2297__7098(.A0N (n_54), .A1N (n_55), .B0 (n_73), .Y
       (n_74));
  OA22X1 g2298__6131(.A0 (n_58), .A1 (n_69), .B0 (n_61), .B1 (n_62), .Y
       (n_75));
  NAND2BX1 g2299__1881(.AN (n_65), .B (n_59), .Y (n_73));
  AOI21X1 g2300__5115(.A0 (n_33), .A1 (n_32), .B0 (n_67), .Y (n_72));
  OR3X1 g2301__7482(.A (n_38), .B (n_49), .C (n_64), .Y (n_71));
  ADDHX1 g2302__4733(.A (in_word[11]), .B (n_34), .CO (n_67), .S
       (n_70));
  NAND2X1 g2303__6161(.A (n_48), .B (n_60), .Y (n_66));
  AND2X1 g2304__9315(.A (n_62), .B (n_61), .Y (n_69));
  NAND2X2 g2305__9945(.A (n_51), .B (n_53), .Y (n_68));
  NOR2XL g2306__2883(.A (n_48), .B (n_60), .Y (n_64));
  AOI22X1 g2307__2346(.A0 (n_45), .A1 (n_50), .B0 (n_46), .B1 (n_44),
       .Y (n_63));
  NOR2X1 g2308__1666(.A (n_55), .B (n_54), .Y (n_65));
  INVX1 g2309(.A (n_57), .Y (n_58));
  CLKXOR2X1 g2310__7410(.A (n_11), .B (n_40), .Y (n_62));
  CLKXOR2X1 g2311__6417(.A (n_22), .B (n_41), .Y (n_61));
  NOR2X1 g2312__5477(.A (n_45), .B (n_50), .Y (n_60));
  XNOR2X1 g2313__2398(.A (n_23), .B (n_39), .Y (n_59));
  XNOR2X1 g2314__5107(.A (n_8), .B (n_43), .Y (n_57));
  CLKXOR2X1 g2315__6260(.A (in_word[11]), .B (n_32), .Y (n_52));
  XNOR2X1 g2316__4319(.A (n_30), .B (n_31), .Y (n_51));
  CLKXOR2X1 g2317__8428(.A (in_word[8]), .B (n_30), .Y (n_56));
  XNOR2X1 g2318__5526(.A (n_9), .B (n_29), .Y (n_55));
  XNOR2X1 g2319__6783(.A (n_23), .B (n_42), .Y (n_54));
  XNOR2X1 g2320__3680(.A (in_word[8]), .B (n_31), .Y (n_53));
  OR2X1 g2321__1617(.A (n_46), .B (n_44), .Y (n_50));
  OR2X1 g2322__2802(.A (n_47), .B (n_36), .Y (n_49));
  NOR2X1 g2323__1705(.A (n_37), .B (n_35), .Y (n_48));
  XNOR2X1 g2324__5122(.A (in_word[10]), .B (n_24), .Y (n_43));
  XNOR2X1 g2325__8246(.A (in_word[15]), .B (n_21), .Y (n_42));
  CLKXOR2X1 g2326__7098(.A (in_word[21]), .B (n_25), .Y (n_47));
  XNOR2X1 g2327__6131(.A (in_word[14]), .B (n_8), .Y (n_41));
  CLKXOR2X1 g2328__1881(.A (in_word[22]), .B (n_26), .Y (n_46));
  XNOR2X1 g2329__5115(.A (in_word[12]), .B (n_24), .Y (n_40));
  CLKXOR2X1 g2330__7482(.A (in_word[20]), .B (n_12), .Y (n_45));
  XNOR2X1 g2331__4733(.A (in_word[9]), .B (n_9), .Y (n_39));
  CLKXOR2X1 g2332__6161(.A (in_word[23]), .B (n_27), .Y (n_44));
  INVX1 g2333(.A (n_33), .Y (n_34));
  CLKXOR2X1 g2334__9315(.A (in_word[17]), .B (n_15), .Y (n_38));
  CLKXOR2X1 g2335__9945(.A (in_word[19]), .B (n_28), .Y (n_37));
  CLKXOR2X1 g2336__2883(.A (in_word[18]), .B (n_13), .Y (n_36));
  CLKXOR2X1 g2337__2346(.A (in_word[16]), .B (n_14), .Y (n_35));
  XNOR2X1 g2338__1666(.A (in_word[13]), .B (n_10), .Y (n_29));
  XNOR2X1 g2339__7410(.A (in_word[9]), .B (n_3), .Y (n_33));
  CLKXOR2X1 g2340__6417(.A (n_10), .B (n_21), .Y (n_32));
  XNOR2X1 g2341__5477(.A (n_22), .B (n_11), .Y (n_31));
  XNOR2X1 g2342__2398(.A (in_word[10]), .B (n_4), .Y (n_30));
  CLKXOR2X1 g2343__5107(.A (in_word[2]), .B (in_word[17]), .Y (n_20));
  CLKXOR2X1 g2344__6260(.A (in_word[4]), .B (in_word[18]), .Y (n_19));
  CLKXOR2X1 g2345__4319(.A (in_word[5]), .B (in_word[22]), .Y (n_18));
  CLKXOR2X1 g2346__8428(.A (in_word[3]), .B (in_word[21]), .Y (n_17));
  CLKXOR2X1 g2347__5526(.A (in_word[1]), .B (in_word[20]), .Y (n_16));
  CLKXOR2X1 g2348__6783(.A (in_word[6]), .B (in_word[27]), .Y (n_28));
  CLKXOR2X1 g2349__3680(.A (in_word[7]), .B (in_word[31]), .Y (n_27));
  CLKXOR2X1 g2350__1617(.A (in_word[5]), .B (in_word[30]), .Y (n_26));
  CLKXOR2X1 g2351__2802(.A (in_word[3]), .B (in_word[29]), .Y (n_25));
  XNOR2X1 g2352__1705(.A (in_word[21]), .B (in_word[16]), .Y (n_24));
  XNOR2X1 g2353__5122(.A (in_word[29]), .B (in_word[24]), .Y (n_23));
  XNOR2X1 g2354__8246(.A (in_word[22]), .B (in_word[19]), .Y (n_22));
  XNOR2X1 g2355__7098(.A (in_word[31]), .B (in_word[26]), .Y (n_21));
  CLKXOR2X1 g2356__6131(.A (in_word[6]), .B (in_word[19]), .Y (n_7));
  CLKXOR2X1 g2357__1881(.A (in_word[0]), .B (in_word[16]), .Y (n_6));
  CLKXOR2X1 g2358__5115(.A (in_word[7]), .B (in_word[23]), .Y (n_5));
  XNOR2X1 g2359__7482(.A (in_word[14]), .B (in_word[12]), .Y (n_4));
  XNOR2X1 g2360__4733(.A (in_word[15]), .B (in_word[13]), .Y (n_3));
  CLKXOR2X1 g2361__6161(.A (in_word[2]), .B (in_word[25]), .Y (n_15));
  CLKXOR2X1 g2362__9315(.A (in_word[0]), .B (in_word[24]), .Y (n_14));
  CLKXOR2X1 g2363__9945(.A (in_word[4]), .B (in_word[26]), .Y (n_13));
  CLKXOR2X1 g2364__2883(.A (in_word[1]), .B (in_word[28]), .Y (n_12));
  XNOR2X1 g2365__2346(.A (in_word[23]), .B (in_word[18]), .Y (n_11));
  XNOR2X1 g2366__1666(.A (in_word[30]), .B (in_word[27]), .Y (n_10));
  XNOR2X1 g2367__7410(.A (in_word[28]), .B (in_word[25]), .Y (n_9));
  XNOR2X1 g2368__6417(.A (in_word[20]), .B (in_word[17]), .Y (n_8));
  BUFX2 drc_bufs2371(.A (n_99), .Y (error_code[0]));
  NOR2BX2 g2__5477(.AN (n_91), .B (n_96), .Y (n_1));
  NOR2BX2 g2375__2398(.AN (n_79), .B (n_83), .Y (n_0));
endmodule

module tbec_encoder(in_word, encoded_word);
  input [15:0] in_word;
  output [31:0] encoded_word;
  wire [15:0] in_word;
  wire [31:0] encoded_word;
  wire n_5, n_6, n_7, n_8, n_13, n_14, n_15, n_16;
  assign encoded_word[16] = 1'b0;
  assign encoded_word[17] = 1'b0;
  assign encoded_word[18] = 1'b0;
  assign encoded_word[19] = 1'b0;
  assign encoded_word[20] = 1'b0;
  assign encoded_word[21] = 1'b0;
  assign encoded_word[22] = 1'b0;
  assign encoded_word[23] = 1'b0;
  assign encoded_word[24] = 1'b0;
  assign encoded_word[25] = 1'b0;
  assign encoded_word[26] = 1'b0;
  assign encoded_word[27] = 1'b0;
  assign encoded_word[28] = 1'b0;
  assign encoded_word[29] = 1'b0;
  assign encoded_word[30] = 1'b0;
  assign encoded_word[31] = 1'b0;
  CLKXOR2X2 g249__5107(.A (n_16), .B (n_6), .Y (encoded_word[14]));
  CLKXOR2X2 g250__6260(.A (n_8), .B (n_7), .Y (encoded_word[12]));
  CLKXOR2X2 g251__4319(.A (n_15), .B (n_13), .Y (encoded_word[15]));
  CLKXOR2X2 g252__8428(.A (n_13), .B (n_14), .Y (encoded_word[11]));
  CLKXOR2X2 g253__5526(.A (n_15), .B (n_5), .Y (encoded_word[9]));
  CLKXOR2X2 g254__6783(.A (n_8), .B (n_16), .Y (encoded_word[10]));
  CLKXOR2X2 g255__3680(.A (n_5), .B (n_14), .Y (encoded_word[13]));
  CLKXOR2X2 g256__1617(.A (n_7), .B (n_6), .Y (encoded_word[8]));
  CLKXOR2X2 g257__2802(.A (in_word[12]), .B (in_word[14]), .Y
       (encoded_word[6]));
  CLKXOR2X2 g258__1705(.A (in_word[8]), .B (in_word[10]), .Y
       (encoded_word[4]));
  CLKXOR2X2 g259__5122(.A (in_word[13]), .B (in_word[15]), .Y
       (encoded_word[7]));
  CLKXOR2X2 g260__8246(.A (in_word[9]), .B (in_word[11]), .Y
       (encoded_word[5]));
  XNOR2X1 g261__7098(.A (in_word[1]), .B (in_word[4]), .Y (n_16));
  XNOR2X1 g262__6131(.A (in_word[2]), .B (in_word[7]), .Y (n_15));
  XNOR2X1 g263__1881(.A (in_word[11]), .B (in_word[14]), .Y (n_14));
  XNOR2X1 g264__5115(.A (in_word[10]), .B (in_word[15]), .Y (n_13));
  CLKXOR2X2 g265__7482(.A (in_word[5]), .B (in_word[7]), .Y
       (encoded_word[3]));
  CLKXOR2X2 g266__4733(.A (in_word[1]), .B (in_word[3]), .Y
       (encoded_word[1]));
  CLKXOR2X2 g267__6161(.A (in_word[4]), .B (in_word[6]), .Y
       (encoded_word[2]));
  CLKXOR2X2 g268__9315(.A (in_word[0]), .B (in_word[2]), .Y
       (encoded_word[0]));
  XNOR2X1 g269__9945(.A (in_word[0]), .B (in_word[5]), .Y (n_8));
  XNOR2X1 g270__2883(.A (in_word[8]), .B (in_word[13]), .Y (n_7));
  XNOR2X1 g271__2346(.A (in_word[9]), .B (in_word[12]), .Y (n_6));
  XNOR2X1 g272__1666(.A (in_word[3]), .B (in_word[6]), .Y (n_5));
endmodule

module tbec_full(tbec_clk, tbec_addr, data_in, mem_we, rst, data_out,
     out_error_code);
  input tbec_clk, mem_we, rst;
  input [7:0] tbec_addr;
  input [15:0] data_in;
  output [15:0] data_out;
  output [1:0] out_error_code;
  wire tbec_clk, mem_we, rst;
  wire [7:0] tbec_addr;
  wire [15:0] data_in;
  wire [15:0] data_out;
  wire [1:0] out_error_code;
  wire [31:0] tbec_enc_out_word;
  wire [31:0] tbec_dec_in_word;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  tbec_memory dut(.clk (tbec_clk), .we (mem_we), .addr (tbec_addr),
       .data_in ({data_in[15], data_in[11], data_in[7], data_in[3],
       data_in[14], data_in[10], data_in[6], data_in[2], data_in[13],
       data_in[9], data_in[5], data_in[1], data_in[12], data_in[8],
       data_in[4], data_in[0], tbec_enc_out_word[15:0]}), .data_out
       (tbec_dec_in_word));
  tbec_decoder tbec_dec_inst(.in_word (tbec_dec_in_word), .decoded_word
       (data_out), .error_code (out_error_code));
  tbec_encoder tbec_enc_inst(.in_word (data_in), .encoded_word
       ({UNCONNECTED14, UNCONNECTED13, UNCONNECTED12, UNCONNECTED11,
       UNCONNECTED10, UNCONNECTED9, UNCONNECTED8, UNCONNECTED7,
       UNCONNECTED6, UNCONNECTED5, UNCONNECTED4, UNCONNECTED3,
       UNCONNECTED2, UNCONNECTED1, UNCONNECTED0, UNCONNECTED,
       tbec_enc_out_word[15:0]}));
endmodule

