
// Generated by Cadence Genus(TM) Synthesis Solution 21.10-p002_1
// Generated on: May 23 2025 15:21:56 -03 (May 23 2025 18:21:56 UTC)

// Verification Directory fv/tbec_decoder 

module tbec_decoder(in_word, decoded_word, error_code);
  input [31:0] in_word;
  output [15:0] decoded_word;
  output [1:0] error_code;
  wire [31:0] in_word;
  wire [15:0] decoded_word;
  wire [1:0] error_code;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_77, n_78, n_79;
  wire n_80, n_81, n_82, n_83, n_84, n_85, n_86, n_87;
  wire n_88, n_89, n_90, n_91, n_92, n_93, n_104, n_111;
  CLKMX2X6 g2212__2398(.A (in_word[19]), .B (n_21), .S0 (n_111), .Y
       (decoded_word[12]));
  CLKMX2X6 g2213__5107(.A (in_word[18]), .B (n_22), .S0 (n_111), .Y
       (decoded_word[8]));
  CLKMX2X6 g2214__6260(.A (in_word[17]), .B (n_25), .S0 (n_111), .Y
       (decoded_word[4]));
  CLKMX2X6 g2215__4319(.A (in_word[16]), .B (n_12), .S0 (n_111), .Y
       (decoded_word[0]));
  CLKMX2X6 g2227__8428(.A (in_word[31]), .B (n_7), .S0 (n_104), .Y
       (decoded_word[15]));
  CLKMX2X6 g2216__5526(.A (in_word[26]), .B (n_0), .S0 (error_code[0]),
       .Y (decoded_word[10]));
  CLKMX2X6 g2224__6783(.A (in_word[30]), .B (n_2), .S0 (n_104), .Y
       (decoded_word[11]));
  CLKMX2X6 g2225__3680(.A (in_word[29]), .B (n_5), .S0 (n_104), .Y
       (decoded_word[7]));
  CLKMX2X6 g2220__1617(.A (in_word[24]), .B (n_8), .S0 (error_code[0]),
       .Y (decoded_word[2]));
  CLKMX2X6 g2222__2802(.A (in_word[27]), .B (n_9), .S0 (error_code[0]),
       .Y (decoded_word[14]));
  CLKMX2X6 g2218__1705(.A (in_word[25]), .B (n_3), .S0 (error_code[0]),
       .Y (decoded_word[6]));
  CLKMX2X6 g2226__5122(.A (in_word[28]), .B (n_4), .S0 (n_104), .Y
       (decoded_word[3]));
  CLKMX2X6 g2223__8246(.A (in_word[23]), .B (n_23), .S0
       (error_code[1]), .Y (decoded_word[13]));
  CLKMX2X6 g2217__7098(.A (in_word[22]), .B (n_24), .S0
       (error_code[1]), .Y (decoded_word[9]));
  CLKMX2X6 g2219__6131(.A (in_word[21]), .B (n_20), .S0
       (error_code[1]), .Y (decoded_word[5]));
  CLKMX2X6 g2221__1881(.A (in_word[20]), .B (n_13), .S0
       (error_code[1]), .Y (decoded_word[1]));
  AND2X1 g2228__5115(.A (error_code[1]), .B (n_91), .Y (n_111));
  AND2X1 g2229__7482(.A (n_90), .B (n_93), .Y (n_104));
  AND2X6 g2230__4733(.A (n_93), .B (n_92), .Y (error_code[0]));
  AND2X6 g2231__6161(.A (n_93), .B (n_89), .Y (error_code[1]));
  INVXL g2234(.A (n_91), .Y (n_92));
  INVXL g2232(.A (n_89), .Y (n_90));
  NOR2X1 g2235__9315(.A (n_87), .B (n_86), .Y (n_91));
  OR2X1 g2233__9945(.A (n_85), .B (n_88), .Y (n_89));
  AOI21X1 g2236__2883(.A0 (n_79), .A1 (n_84), .B0 (n_87), .Y (n_88));
  AOI21X1 g2237__2346(.A0 (n_83), .A1 (n_82), .B0 (n_85), .Y (n_86));
  MX2X1 g2238__1666(.A (n_57), .B (n_69), .S0 (n_78), .Y (n_93));
  OAI21X1 g2239__7410(.A0 (n_81), .A1 (n_80), .B0 (n_83), .Y (n_84));
  OAI2BB1X1 g2240__6417(.A0N (n_81), .A1N (n_80), .B0 (n_79), .Y
       (n_82));
  AOI221X2 g2245__5477(.A0 (n_37), .A1 (n_36), .B0 (n_32), .B1 (n_33),
       .C0 (n_73), .Y (n_78));
  NOR2BX1 g2242__2398(.AN (n_74), .B (n_75), .Y (n_87));
  OR2X1 g2243__5107(.A (n_77), .B (n_76), .Y (n_79));
  NAND2X2 g2244__6260(.A (n_77), .B (n_76), .Y (n_83));
  NOR2BX1 g2241__4319(.AN (n_75), .B (n_74), .Y (n_85));
  ADDHX1 g2246__8428(.A (n_67), .B (n_66), .CO (n_74), .S (n_76));
  NAND2X1 g2248__5526(.A (n_53), .B (n_70), .Y (n_73));
  XNOR2X1 g2249__6783(.A (n_72), .B (n_71), .Y (n_77));
  NOR2X1 g2250__3680(.A (n_72), .B (n_71), .Y (n_75));
  AOI22X1 g2251__1617(.A0 (n_63), .A1 (n_64), .B0 (n_47), .B1 (n_46),
       .Y (n_70));
  AOI21X1 g2247__2802(.A0 (n_65), .A1 (n_68), .B0 (n_60), .Y (n_69));
  OA22X1 g2255__1705(.A0 (n_58), .A1 (n_68), .B0 (n_55), .B1 (n_54), .Y
       (n_71));
  AOI211X2 g2253__5122(.A0 (n_30), .A1 (n_44), .B0 (n_56), .C0 (n_38),
       .Y (n_67));
  OAI22X1 g2254__8246(.A0 (n_59), .A1 (n_65), .B0 (n_51), .B1 (n_52),
       .Y (n_66));
  OAI21X1 g2256__7098(.A0 (n_62), .A1 (n_61), .B0 (n_50), .Y (n_64));
  NAND2X1 g2260__6131(.A (n_62), .B (n_61), .Y (n_63));
  AND4X1 g2252__1881(.A (n_59), .B (n_58), .C (n_45), .D (n_57), .Y
       (n_60));
  ADDHX1 g2257__5115(.A (in_word[11]), .B (n_31), .CO (n_56), .S
       (n_81));
  AND2X1 g2258__7482(.A (n_55), .B (n_54), .Y (n_68));
  OR2X1 g2259__4733(.A (n_42), .B (n_57), .Y (n_72));
  AOI22X1 g2261__6161(.A0 (n_49), .A1 (n_48), .B0 (n_35), .B1 (n_34),
       .Y (n_53));
  AND2X1 g2262__9315(.A (n_52), .B (n_51), .Y (n_65));
  NOR2X1 g2263__9945(.A (n_49), .B (n_48), .Y (n_50));
  NOR2X1 g2264__2883(.A (n_47), .B (n_46), .Y (n_61));
  XNOR2X1 g2269__2346(.A (in_word[11]), .B (n_44), .Y (n_45));
  CLKXOR2X1 g2266__1666(.A (n_17), .B (n_29), .Y (n_55));
  CLKXOR2X1 g2265__7410(.A (n_43), .B (n_26), .Y (n_54));
  CLKXOR2X1 g2268__6417(.A (n_43), .B (n_18), .Y (n_58));
  CLKXOR2X1 g2267__5477(.A (n_40), .B (n_28), .Y (n_59));
  CLKXOR2X1 g2270__2398(.A (n_41), .B (n_39), .Y (n_42));
  CLKXOR2X1 g2271__5107(.A (in_word[8]), .B (n_41), .Y (n_80));
  CLKXOR2X1 g2272__6260(.A (n_27), .B (n_19), .Y (n_51));
  CLKXOR2X1 g2273__4319(.A (n_40), .B (n_16), .Y (n_52));
  CLKXOR2X1 g2274__8428(.A (in_word[8]), .B (n_39), .Y (n_57));
  NOR2X1 g2275__5526(.A (in_word[11]), .B (n_44), .Y (n_38));
  OR2X1 g2276__6783(.A (n_37), .B (n_36), .Y (n_48));
  OR2X1 g2277__3680(.A (n_35), .B (n_34), .Y (n_46));
  NOR2X1 g2278__1617(.A (n_33), .B (n_32), .Y (n_62));
  INVXL g2288(.A (n_30), .Y (n_31));
  XNOR2X1 g2284__2802(.A (in_word[12]), .B (n_14), .Y (n_29));
  XNOR2X1 g2286__1705(.A (in_word[9]), .B (n_27), .Y (n_28));
  XNOR2X1 g2283__5122(.A (in_word[14]), .B (n_15), .Y (n_26));
  CLKXOR2X1 g2285__8246(.A (in_word[17]), .B (n_25), .Y (n_49));
  CLKXOR2X1 g2289__7098(.A (in_word[22]), .B (n_24), .Y (n_47));
  CLKXOR2X1 g2287__6131(.A (in_word[23]), .B (n_23), .Y (n_34));
  CLKXOR2X1 g2290__1881(.A (in_word[18]), .B (n_22), .Y (n_36));
  CLKXOR2X1 g2291__5115(.A (in_word[19]), .B (n_21), .Y (n_33));
  CLKXOR2X1 g2292__7482(.A (in_word[21]), .B (n_20), .Y (n_37));
  XNOR2X1 g2293__4733(.A (in_word[13]), .B (n_11), .Y (n_19));
  XNOR2X1 g2279__6161(.A (in_word[10]), .B (n_17), .Y (n_18));
  XNOR2X1 g2280__9315(.A (in_word[15]), .B (n_10), .Y (n_16));
  XNOR2X1 g2296__9945(.A (n_15), .B (n_14), .Y (n_39));
  XNOR2X1 g2297__2883(.A (in_word[10]), .B (n_6), .Y (n_41));
  XNOR2X1 g2294__2346(.A (in_word[9]), .B (n_1), .Y (n_30));
  CLKXOR2X1 g2282__1666(.A (in_word[20]), .B (n_13), .Y (n_35));
  CLKXOR2X1 g2281__7410(.A (in_word[16]), .B (n_12), .Y (n_32));
  CLKXOR2X1 g2295__6417(.A (n_11), .B (n_10), .Y (n_44));
  CLKXOR2X1 g2312__5477(.A (in_word[6]), .B (in_word[19]), .Y (n_9));
  CLKXOR2X1 g2298__2398(.A (in_word[0]), .B (in_word[16]), .Y (n_8));
  CLKXOR2X1 g2313__5107(.A (in_word[7]), .B (in_word[23]), .Y (n_7));
  XNOR2X1 g2314__6260(.A (in_word[12]), .B (in_word[14]), .Y (n_6));
  CLKXOR2X1 g2299__4319(.A (in_word[3]), .B (in_word[21]), .Y (n_5));
  CLKXOR2X1 g2300__8428(.A (in_word[1]), .B (in_word[20]), .Y (n_4));
  CLKXOR2X1 g2301__5526(.A (in_word[2]), .B (in_word[17]), .Y (n_3));
  CLKXOR2X1 g2302__6783(.A (in_word[5]), .B (in_word[22]), .Y (n_2));
  CLKXOR2X1 g2316__3680(.A (in_word[5]), .B (in_word[30]), .Y (n_24));
  CLKXOR2X1 g2304__1617(.A (in_word[1]), .B (in_word[28]), .Y (n_13));
  CLKXOR2X1 g2320__2802(.A (in_word[4]), .B (in_word[26]), .Y (n_22));
  CLKXOR2X1 g2305__1705(.A (in_word[7]), .B (in_word[31]), .Y (n_23));
  CLKXOR2X1 g2303__5122(.A (in_word[0]), .B (in_word[24]), .Y (n_12));
  XNOR2X1 g2315__8246(.A (in_word[13]), .B (in_word[15]), .Y (n_1));
  CLKXOR2X1 g2311__7098(.A (in_word[4]), .B (in_word[18]), .Y (n_0));
  XNOR2X1 g2308__6131(.A (in_word[19]), .B (in_word[22]), .Y (n_15));
  XNOR2X1 g2306__1881(.A (in_word[26]), .B (in_word[31]), .Y (n_10));
  XNOR2X1 g2309__5115(.A (in_word[17]), .B (in_word[20]), .Y (n_43));
  XNOR2X1 g2310__7482(.A (in_word[16]), .B (in_word[21]), .Y (n_17));
  CLKXOR2X1 g2319__4733(.A (in_word[3]), .B (in_word[29]), .Y (n_20));
  XNOR2X1 g2323__6161(.A (in_word[18]), .B (in_word[23]), .Y (n_14));
  XNOR2X1 g2321__9315(.A (in_word[27]), .B (in_word[30]), .Y (n_11));
  CLKXOR2X1 g2318__9945(.A (in_word[6]), .B (in_word[27]), .Y (n_21));
  XNOR2X1 g2307__2883(.A (in_word[24]), .B (in_word[29]), .Y (n_40));
  XNOR2X1 g2322__2346(.A (in_word[25]), .B (in_word[28]), .Y (n_27));
  CLKXOR2X1 g2317__1666(.A (in_word[2]), .B (in_word[25]), .Y (n_25));
endmodule

