###############################################################
#  Generated by:      Cadence Innovus 21.15-s110_1
#  OS:                Linux x86_64(Host ID cinova05.lesc.ufc.br)
#  Generated on:      Fri May 23 15:38:32 2025
#  Design:            tbec_decoder
#  Command:           create_clock_tree_spec -out_file /home/cinovador/Documents/pos_fase_2/ecc_rtl_codes/tbec_decoder/backend/layout/scripts/cts.spec
###############################################################
