/*
###############################################################
#  Generated by:      Cadence Innovus 21.15-s110_1
#  OS:                Linux x86_64(Host ID cinova05.lesc.ufc.br)
#  Generated on:      Fri May 23 15:51:27 2025
#  Design:            tbec_decoder
#  Command:           write_netlist /home/cinovador/Documents/pos_fase_2/ecc_rtl_codes/tbec_decoder/backend/layout/deliverables/tbec_decoder_layout.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 21.10-p002_1
// Generated on: May 23 2025 15:21:56 -03 (May 23 2025 18:21:56 UTC)
// Verification Directory fv/tbec_decoder 
module tbec_decoder (
	in_word, 
	decoded_word, 
	error_code);
   input [31:0] in_word;
   output [15:0] decoded_word;
   output [1:0] error_code;

   // Internal wires
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;
   wire n_76;
   wire n_77;
   wire n_78;
   wire n_79;
   wire n_80;
   wire n_81;
   wire n_82;
   wire n_83;
   wire n_84;
   wire n_85;
   wire n_86;
   wire n_87;
   wire n_88;
   wire n_89;
   wire n_90;
   wire n_91;
   wire n_92;
   wire n_93;
   wire n_104;
   wire n_111;

   CLKMX2X6 g2212__2398 (.Y(decoded_word[12]),
	.A(in_word[19]),
	.B(n_21),
	.S0(n_111));
   CLKMX2X6 g2213__5107 (.Y(decoded_word[8]),
	.A(in_word[18]),
	.B(n_22),
	.S0(n_111));
   CLKMX2X6 g2214__6260 (.Y(decoded_word[4]),
	.A(in_word[17]),
	.B(n_25),
	.S0(n_111));
   CLKMX2X6 g2215__4319 (.Y(decoded_word[0]),
	.A(in_word[16]),
	.B(n_12),
	.S0(n_111));
   CLKMX2X6 g2227__8428 (.Y(decoded_word[15]),
	.A(in_word[31]),
	.B(n_7),
	.S0(n_104));
   CLKMX2X6 g2216__5526 (.Y(decoded_word[10]),
	.A(in_word[26]),
	.B(n_0),
	.S0(error_code[0]));
   CLKMX2X6 g2224__6783 (.Y(decoded_word[11]),
	.A(in_word[30]),
	.B(n_2),
	.S0(n_104));
   CLKMX2X6 g2225__3680 (.Y(decoded_word[7]),
	.A(in_word[29]),
	.B(n_5),
	.S0(n_104));
   CLKMX2X6 g2220__1617 (.Y(decoded_word[2]),
	.A(in_word[24]),
	.B(n_8),
	.S0(error_code[0]));
   CLKMX2X6 g2222__2802 (.Y(decoded_word[14]),
	.A(in_word[27]),
	.B(n_9),
	.S0(error_code[0]));
   CLKMX2X6 g2218__1705 (.Y(decoded_word[6]),
	.A(in_word[25]),
	.B(n_3),
	.S0(error_code[0]));
   CLKMX2X6 g2226__5122 (.Y(decoded_word[3]),
	.A(in_word[28]),
	.B(n_4),
	.S0(n_104));
   CLKMX2X6 g2223__8246 (.Y(decoded_word[13]),
	.A(in_word[23]),
	.B(n_23),
	.S0(error_code[1]));
   CLKMX2X6 g2217__7098 (.Y(decoded_word[9]),
	.A(in_word[22]),
	.B(n_24),
	.S0(error_code[1]));
   CLKMX2X6 g2219__6131 (.Y(decoded_word[5]),
	.A(in_word[21]),
	.B(n_20),
	.S0(error_code[1]));
   CLKMX2X6 g2221__1881 (.Y(decoded_word[1]),
	.A(in_word[20]),
	.B(n_13),
	.S0(error_code[1]));
   AND2X1 g2228__5115 (.Y(n_111),
	.A(error_code[1]),
	.B(n_91));
   AND2X1 g2229__7482 (.Y(n_104),
	.A(n_90),
	.B(n_93));
   AND2X6 g2230__4733 (.Y(error_code[0]),
	.A(n_93),
	.B(n_92));
   AND2X6 g2231__6161 (.Y(error_code[1]),
	.A(n_93),
	.B(n_89));
   INVXL g2234 (.Y(n_92),
	.A(n_91));
   INVXL g2232 (.Y(n_90),
	.A(n_89));
   NOR2X1 g2235__9315 (.Y(n_91),
	.A(n_87),
	.B(n_86));
   OR2X1 g2233__9945 (.Y(n_89),
	.A(n_85),
	.B(n_88));
   AOI21X1 g2236__2883 (.Y(n_88),
	.A0(n_79),
	.A1(n_84),
	.B0(n_87));
   AOI21X1 g2237__2346 (.Y(n_86),
	.A0(n_83),
	.A1(n_82),
	.B0(n_85));
   MX2X1 g2238__1666 (.Y(n_93),
	.A(n_57),
	.B(n_69),
	.S0(n_78));
   OAI21X1 g2239__7410 (.Y(n_84),
	.A0(n_81),
	.A1(n_80),
	.B0(n_83));
   OAI2BB1X1 g2240__6417 (.Y(n_82),
	.A0N(n_81),
	.A1N(n_80),
	.B0(n_79));
   AOI221X2 g2245__5477 (.Y(n_78),
	.A0(n_37),
	.A1(n_36),
	.B0(n_32),
	.B1(n_33),
	.C0(n_73));
   NOR2BX1 g2242__2398 (.Y(n_87),
	.AN(n_74),
	.B(n_75));
   OR2X1 g2243__5107 (.Y(n_79),
	.A(n_77),
	.B(n_76));
   NAND2X2 g2244__6260 (.Y(n_83),
	.A(n_77),
	.B(n_76));
   NOR2BX1 g2241__4319 (.Y(n_85),
	.AN(n_75),
	.B(n_74));
   ADDHX1 g2246__8428 (.CO(n_74),
	.S(n_76),
	.A(n_67),
	.B(n_66));
   NAND2X1 g2248__5526 (.Y(n_73),
	.A(n_53),
	.B(n_70));
   XNOR2X1 g2249__6783 (.Y(n_77),
	.A(n_72),
	.B(n_71));
   NOR2X1 g2250__3680 (.Y(n_75),
	.A(n_72),
	.B(n_71));
   AOI22X1 g2251__1617 (.Y(n_70),
	.A0(n_63),
	.A1(n_64),
	.B0(n_47),
	.B1(n_46));
   AOI21X1 g2247__2802 (.Y(n_69),
	.A0(n_65),
	.A1(n_68),
	.B0(n_60));
   OA22X1 g2255__1705 (.Y(n_71),
	.A0(n_58),
	.A1(n_68),
	.B0(n_55),
	.B1(n_54));
   AOI211X2 g2253__5122 (.Y(n_67),
	.A0(n_30),
	.A1(n_44),
	.B0(n_56),
	.C0(n_38));
   OAI22X1 g2254__8246 (.Y(n_66),
	.A0(n_59),
	.A1(n_65),
	.B0(n_51),
	.B1(n_52));
   OAI21X1 g2256__7098 (.Y(n_64),
	.A0(n_62),
	.A1(n_61),
	.B0(n_50));
   NAND2X1 g2260__6131 (.Y(n_63),
	.A(n_62),
	.B(n_61));
   AND4X1 g2252__1881 (.Y(n_60),
	.A(n_59),
	.B(n_58),
	.C(n_45),
	.D(n_57));
   ADDHX1 g2257__5115 (.CO(n_56),
	.S(n_81),
	.A(in_word[11]),
	.B(n_31));
   AND2X1 g2258__7482 (.Y(n_68),
	.A(n_55),
	.B(n_54));
   OR2X1 g2259__4733 (.Y(n_72),
	.A(n_42),
	.B(n_57));
   AOI22X1 g2261__6161 (.Y(n_53),
	.A0(n_49),
	.A1(n_48),
	.B0(n_35),
	.B1(n_34));
   AND2X1 g2262__9315 (.Y(n_65),
	.A(n_52),
	.B(n_51));
   NOR2X1 g2263__9945 (.Y(n_50),
	.A(n_49),
	.B(n_48));
   NOR2X1 g2264__2883 (.Y(n_61),
	.A(n_47),
	.B(n_46));
   XNOR2X1 g2269__2346 (.Y(n_45),
	.A(in_word[11]),
	.B(n_44));
   CLKXOR2X1 g2266__1666 (.Y(n_55),
	.A(n_17),
	.B(n_29));
   CLKXOR2X1 g2265__7410 (.Y(n_54),
	.A(n_43),
	.B(n_26));
   CLKXOR2X1 g2268__6417 (.Y(n_58),
	.A(n_43),
	.B(n_18));
   CLKXOR2X1 g2267__5477 (.Y(n_59),
	.A(n_40),
	.B(n_28));
   CLKXOR2X1 g2270__2398 (.Y(n_42),
	.A(n_41),
	.B(n_39));
   CLKXOR2X1 g2271__5107 (.Y(n_80),
	.A(in_word[8]),
	.B(n_41));
   CLKXOR2X1 g2272__6260 (.Y(n_51),
	.A(n_27),
	.B(n_19));
   CLKXOR2X1 g2273__4319 (.Y(n_52),
	.A(n_40),
	.B(n_16));
   CLKXOR2X1 g2274__8428 (.Y(n_57),
	.A(in_word[8]),
	.B(n_39));
   NOR2X1 g2275__5526 (.Y(n_38),
	.A(in_word[11]),
	.B(n_44));
   OR2X1 g2276__6783 (.Y(n_48),
	.A(n_37),
	.B(n_36));
   OR2X1 g2277__3680 (.Y(n_46),
	.A(n_35),
	.B(n_34));
   NOR2X1 g2278__1617 (.Y(n_62),
	.A(n_33),
	.B(n_32));
   INVXL g2288 (.Y(n_31),
	.A(n_30));
   XNOR2X1 g2284__2802 (.Y(n_29),
	.A(in_word[12]),
	.B(n_14));
   XNOR2X1 g2286__1705 (.Y(n_28),
	.A(in_word[9]),
	.B(n_27));
   XNOR2X1 g2283__5122 (.Y(n_26),
	.A(in_word[14]),
	.B(n_15));
   CLKXOR2X1 g2285__8246 (.Y(n_49),
	.A(in_word[17]),
	.B(n_25));
   CLKXOR2X1 g2289__7098 (.Y(n_47),
	.A(in_word[22]),
	.B(n_24));
   CLKXOR2X1 g2287__6131 (.Y(n_34),
	.A(in_word[23]),
	.B(n_23));
   CLKXOR2X1 g2290__1881 (.Y(n_36),
	.A(in_word[18]),
	.B(n_22));
   CLKXOR2X1 g2291__5115 (.Y(n_33),
	.A(in_word[19]),
	.B(n_21));
   CLKXOR2X1 g2292__7482 (.Y(n_37),
	.A(in_word[21]),
	.B(n_20));
   XNOR2X1 g2293__4733 (.Y(n_19),
	.A(in_word[13]),
	.B(n_11));
   XNOR2X1 g2279__6161 (.Y(n_18),
	.A(in_word[10]),
	.B(n_17));
   XNOR2X1 g2280__9315 (.Y(n_16),
	.A(in_word[15]),
	.B(n_10));
   XNOR2X1 g2296__9945 (.Y(n_39),
	.A(n_15),
	.B(n_14));
   XNOR2X1 g2297__2883 (.Y(n_41),
	.A(in_word[10]),
	.B(n_6));
   XNOR2X1 g2294__2346 (.Y(n_30),
	.A(in_word[9]),
	.B(n_1));
   CLKXOR2X1 g2282__1666 (.Y(n_35),
	.A(in_word[20]),
	.B(n_13));
   CLKXOR2X1 g2281__7410 (.Y(n_32),
	.A(in_word[16]),
	.B(n_12));
   CLKXOR2X1 g2295__6417 (.Y(n_44),
	.A(n_11),
	.B(n_10));
   CLKXOR2X1 g2312__5477 (.Y(n_9),
	.A(in_word[6]),
	.B(in_word[19]));
   CLKXOR2X1 g2298__2398 (.Y(n_8),
	.A(in_word[0]),
	.B(in_word[16]));
   CLKXOR2X1 g2313__5107 (.Y(n_7),
	.A(in_word[7]),
	.B(in_word[23]));
   XNOR2X1 g2314__6260 (.Y(n_6),
	.A(in_word[12]),
	.B(in_word[14]));
   CLKXOR2X1 g2299__4319 (.Y(n_5),
	.A(in_word[3]),
	.B(in_word[21]));
   CLKXOR2X1 g2300__8428 (.Y(n_4),
	.A(in_word[1]),
	.B(in_word[20]));
   CLKXOR2X1 g2301__5526 (.Y(n_3),
	.A(in_word[2]),
	.B(in_word[17]));
   CLKXOR2X1 g2302__6783 (.Y(n_2),
	.A(in_word[5]),
	.B(in_word[22]));
   CLKXOR2X1 g2316__3680 (.Y(n_24),
	.A(in_word[5]),
	.B(in_word[30]));
   CLKXOR2X1 g2304__1617 (.Y(n_13),
	.A(in_word[1]),
	.B(in_word[28]));
   CLKXOR2X1 g2320__2802 (.Y(n_22),
	.A(in_word[4]),
	.B(in_word[26]));
   CLKXOR2X1 g2305__1705 (.Y(n_23),
	.A(in_word[7]),
	.B(in_word[31]));
   CLKXOR2X1 g2303__5122 (.Y(n_12),
	.A(in_word[0]),
	.B(in_word[24]));
   XNOR2X1 g2315__8246 (.Y(n_1),
	.A(in_word[13]),
	.B(in_word[15]));
   CLKXOR2X1 g2311__7098 (.Y(n_0),
	.A(in_word[4]),
	.B(in_word[18]));
   XNOR2X1 g2308__6131 (.Y(n_15),
	.A(in_word[19]),
	.B(in_word[22]));
   XNOR2X1 g2306__1881 (.Y(n_10),
	.A(in_word[26]),
	.B(in_word[31]));
   XNOR2X1 g2309__5115 (.Y(n_43),
	.A(in_word[17]),
	.B(in_word[20]));
   XNOR2X1 g2310__7482 (.Y(n_17),
	.A(in_word[16]),
	.B(in_word[21]));
   CLKXOR2X1 g2319__4733 (.Y(n_20),
	.A(in_word[3]),
	.B(in_word[29]));
   XNOR2X1 g2323__6161 (.Y(n_14),
	.A(in_word[18]),
	.B(in_word[23]));
   XNOR2X1 g2321__9315 (.Y(n_11),
	.A(in_word[27]),
	.B(in_word[30]));
   CLKXOR2X1 g2318__9945 (.Y(n_21),
	.A(in_word[6]),
	.B(in_word[27]));
   XNOR2X1 g2307__2883 (.Y(n_40),
	.A(in_word[24]),
	.B(in_word[29]));
   XNOR2X1 g2322__2346 (.Y(n_27),
	.A(in_word[25]),
	.B(in_word[28]));
   CLKXOR2X1 g2317__1666 (.Y(n_25),
	.A(in_word[2]),
	.B(in_word[25]));
endmodule

