/*
###############################################################
#  Generated by:      Cadence Innovus 21.15-s110_1
#  OS:                Linux x86_64(Host ID cinova05.lesc.ufc.br)
#  Generated on:      Fri May 23 16:08:21 2025
#  Design:            tbec_encoder
#  Command:           write_netlist /home/cinovador/Documents/pos_fase_2/ecc_rtl_codes/tbec_encoder/backend/layout/deliverables/tbec_encoder_layout.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 21.10-p002_1
// Generated on: May 23 2025 16:01:30 -03 (May 23 2025 19:01:30 UTC)
// Verification Directory fv/tbec_encoder 
module tbec_encoder (
	in_word, 
	encoded_word);
   input [15:0] in_word;
   output [31:0] encoded_word;

   // Internal wires
   wire n_8;
   wire n_9;
   wire n_11;
   wire n_12;
   wire n_14;
   wire n_15;
   wire n_17;
   wire n_18;

   assign encoded_word[16] = in_word[0] ;
   assign encoded_word[17] = in_word[4] ;
   assign encoded_word[18] = in_word[8] ;
   assign encoded_word[19] = in_word[12] ;
   assign encoded_word[20] = in_word[1] ;
   assign encoded_word[21] = in_word[5] ;
   assign encoded_word[22] = in_word[9] ;
   assign encoded_word[23] = in_word[13] ;
   assign encoded_word[24] = in_word[2] ;
   assign encoded_word[25] = in_word[6] ;
   assign encoded_word[26] = in_word[10] ;
   assign encoded_word[27] = in_word[14] ;
   assign encoded_word[28] = in_word[3] ;
   assign encoded_word[29] = in_word[7] ;
   assign encoded_word[30] = in_word[11] ;
   assign encoded_word[31] = in_word[15] ;

   CLKXOR2X8 g250__2398 (.Y(encoded_word[13]),
	.A(n_17),
	.B(n_11));
   CLKXOR2X8 g252__5107 (.Y(encoded_word[14]),
	.A(n_14),
	.B(n_8));
   CLKXOR2X8 g251__6260 (.Y(encoded_word[15]),
	.A(n_18),
	.B(n_12));
   CLKXOR2X8 g249__4319 (.Y(encoded_word[12]),
	.A(n_15),
	.B(n_9));
   CLKXOR2X8 g253__8428 (.Y(encoded_word[9]),
	.A(n_18),
	.B(n_17));
   CLKXOR2X8 g254__5526 (.Y(encoded_word[10]),
	.A(n_15),
	.B(n_14));
   CLKXOR2X8 g255__6783 (.Y(encoded_word[11]),
	.A(n_12),
	.B(n_11));
   CLKXOR2X8 g256__3680 (.Y(encoded_word[8]),
	.A(n_9),
	.B(n_8));
   CLKXOR2X8 g257__1617 (.Y(encoded_word[7]),
	.A(in_word[13]),
	.B(in_word[15]));
   CLKXOR2X8 g265__2802 (.Y(encoded_word[1]),
	.A(in_word[1]),
	.B(in_word[3]));
   CLKXOR2X8 g266__1705 (.Y(encoded_word[0]),
	.A(in_word[0]),
	.B(in_word[2]));
   CLKXOR2X8 g267__5122 (.Y(encoded_word[2]),
	.A(in_word[4]),
	.B(in_word[6]));
   XNOR2X1 g268__8246 (.Y(n_15),
	.A(in_word[0]),
	.B(in_word[5]));
   XNOR2X1 g271__7098 (.Y(n_14),
	.A(in_word[1]),
	.B(in_word[4]));
   XNOR2X1 g263__6131 (.Y(n_17),
	.A(in_word[3]),
	.B(in_word[6]));
   XNOR2X1 g270__1881 (.Y(n_9),
	.A(in_word[8]),
	.B(in_word[13]));
   CLKXOR2X8 g258__5115 (.Y(encoded_word[5]),
	.A(in_word[9]),
	.B(in_word[11]));
   CLKXOR2X8 g261__7482 (.Y(encoded_word[3]),
	.A(in_word[5]),
	.B(in_word[7]));
   CLKXOR2X8 g260__4733 (.Y(encoded_word[4]),
	.A(in_word[8]),
	.B(in_word[10]));
   CLKXOR2X8 g259__6161 (.Y(encoded_word[6]),
	.A(in_word[12]),
	.B(in_word[14]));
   XNOR2X1 g269__9315 (.Y(n_11),
	.A(in_word[11]),
	.B(in_word[14]));
   XNOR2X1 g272__9945 (.Y(n_8),
	.A(in_word[9]),
	.B(in_word[12]));
   XNOR2X1 g264__2883 (.Y(n_12),
	.A(in_word[10]),
	.B(in_word[15]));
   XNOR2X1 g262__2346 (.Y(n_18),
	.A(in_word[2]),
	.B(in_word[7]));
endmodule

