###############################################################
#  Generated by:      Cadence Innovus 21.15-s110_1
#  OS:                Linux x86_64(Host ID cinova05.lesc.ufc.br)
#  Generated on:      Thu May 29 10:10:50 2025
#  Design:            tbec_full
#  Command:           create_clock_tree_spec -out_file /home/cinovador/Documents/pos_fase_2/ecc_rtl_codes/tbec_full/backend/layout/scripts/cts.spec
###############################################################
#-------------------------------------------------------------------------------
# Clock tree setup script - dialect: Common UI
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------

if { [get_db clock_trees] != {} } {
  error {Cannot run clock tree spec: clock trees are already defined.}
}

namespace eval ::ccopt {}
namespace eval ::ccopt::ilm {}
set ::ccopt::ilm::ccoptSpecRestoreData {}
# Start by checking for unflattened ILMs.
# Will flatten if so and then check the db sync.
if { [catch {ccopt_check_and_flatten_ilms_no_restore}] } {
  return -code error
}
# cache the value of the restore command output by the ILM flattening code
set ::ccopt::ilm::ccoptSpecRestoreData $::ccopt::ilm::ccoptRestoreILMState

# The following pins are clock sources
set_db port:clk .cts_is_sdc_clock_root true

# Clocks present at pin clk
#   clk (period 50.000ns) in timing_config normal_genus_slow_max([/home/cinovador/Documents/pos_fase_2/ecc_rtl_codes/tbec_full/backend/synthesis/constraints/tbec_full.sdc])
create_clock_tree -name clk -source clk -no_skew_group
# Clock period setting for source pin of clk
set_db port:clk .cts_clock_period 50

##############################################################################
##
## Timing connectivity based skew groups: off
##
##############################################################################
set_db cts_timing_connectivity_info {}

# Skew group to balance non generated clock:clk in timing_config:normal_genus_slow_max (sdc /home/cinovador/Documents/pos_fase_2/ecc_rtl_codes/tbec_full/backend/synthesis/constraints/tbec_full.sdc)
create_skew_group -name clk/normal_genus_slow_max -sources clk -auto_sinks
set_db skew_group:clk/normal_genus_slow_max .cts_skew_group_include_source_latency true
set_db skew_group:clk/normal_genus_slow_max .cts_skew_group_target_insertion_delay 0.105
set_db skew_group:clk/normal_genus_slow_max .cts_skew_group_created_from_clock clk
set_db skew_group:clk/normal_genus_slow_max .cts_skew_group_created_from_constraint_mode normal_genus_slow_max
set_db skew_group:clk/normal_genus_slow_max .cts_skew_group_created_from_delay_corners {slow_max fast_min}

set_db net:clk .cts_ideal_net true
set_db port:clk .cts_annotated_transition_early_rise -index delay_corner:slow_max 0.000
set_db port:clk .cts_annotated_transition_early_fall -index delay_corner:slow_max 0.000
set_db port:clk .cts_annotated_transition_late_rise -index delay_corner:slow_max 0.000
set_db port:clk .cts_annotated_transition_late_fall -index delay_corner:slow_max 0.000
set_db port:clk .cts_annotated_transition_early_rise -index delay_corner:fast_min 0.000
set_db port:clk .cts_annotated_transition_early_fall -index delay_corner:fast_min 0.000
set_db port:clk .cts_annotated_transition_late_rise -index delay_corner:fast_min 0.000
set_db port:clk .cts_annotated_transition_late_fall -index delay_corner:fast_min 0.000

check_clock_tree_convergence
# Restore the ILM status if possible
if { [get_db ccopt_auto_design_state_for_ilms] == 0 } {
  if {$::ccopt::ilm::ccoptSpecRestoreData != {} } {
    eval $::ccopt::ilm::ccoptSpecRestoreData
  }
}

